<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE System [
<!ELEMENT System (Elements)>
<!ATTLIST System
Lang CDATA #REQUIRED
>
<!ELEMENT Elements (Element*)>
<!ATTLIST Elements
NumItems CDATA #REQUIRED
>
<!ELEMENT Element (Show,Position,Parameters,InternalInputs,InternalOutputs,PublishedInputs,PublishedOutputs,InputLinks,OutputLinks)>
<!ATTLIST Element
ClassID CDATA #REQUIRED
ParentID CDATA #REQUIRED
ID ID #REQUIRED
Permanent (True | False) #REQUIRED
>
<!ELEMENT Show EMPTY>
<!ATTLIST Show
Class (True | False) #REQUIRED
Name (True | False) #REQUIRED
Image (True | False) #REQUIRED
>
<!ELEMENT Position EMPTY>
<!ATTLIST Position
Left CDATA #REQUIRED
Top CDATA #REQUIRED
>
<!ELEMENT Parameters (Parameter*)>
<!ATTLIST Parameters
NumItems CDATA #REQUIRED
>
<!ELEMENT Parameter (#PCDATA | EMPTY)*>
<!ATTLIST Parameter
ID CDATA #REQUIRED
Indent CDATA #IMPLIED
>
<!ELEMENT InternalInputs (iContact*)>
<!ATTLIST InternalInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT InternalOutputs (iContact*)>
<!ATTLIST InternalOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT iContact EMPTY>
<!ATTLIST iContact
ID CDATA #REQUIRED
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
>
<!ELEMENT PublishedInputs (pContact*)>
<!ATTLIST PublishedInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT PublishedOutputs (pContact*)>
<!ATTLIST PublishedOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT pContact EMPTY>
<!ATTLIST pContact
ID CDATA #REQUIRED
PublicID CDATA #REQUIRED
PublicName CDATA #REQUIRED
>
<!ELEMENT InputLinks (Contact*)>
<!ELEMENT OutputLinks (Contact*)>
<!ELEMENT Contact (Link*)>
<!ATTLIST Contact
ID CDATA #REQUIRED
>
<!ELEMENT Link (Points?)>
<!ATTLIST Link
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
Color CDATA #IMPLIED
Informational (True | False) #REQUIRED
>
<!ELEMENT Points (#PCDATA | EMPTY)*>
<!ATTLIST Points
NumItems CDATA #REQUIRED
>
]>
<System Lang="">
 <Elements NumItems="98">
  <Element ClassID="clsE_Phase" ParentID="" ID="MainPhase" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="181" Top="108"/>
   <Parameters NumItems="3">
    <Parameter ID="Uw" Indent="0">0</Parameter>
    <Parameter ID="Nc" Indent="0">1</Parameter>
    <Parameter ID="Source" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Model">
     <Link ElementID="Model" ContID="Carrier" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Nu">
     <Link ElementID="Nu" ContID="PhasePrm" Color="#808040" Informational="False">
      <Points NumItems="2">337,169,359,47</Points>
     </Link>
    </Contact>
    <Contact ID="T">
     <Link ElementID="T" ContID="PhasePrm" Color="#808040" Informational="False">
      <Points NumItems="1">361,155</Points>
     </Link>
    </Contact>
    <Contact ID="U">
     <Link ElementID="U" ContID="PhasePrm" Color="#0080FF" Informational="False">
      <Points NumItems="1">379,176</Points>
     </Link>
    </Contact>
    <Contact ID="Define">
     <Link ElementID="Nu" ContID="Phase" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="T" ContID="Phase" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="U" ContID="Phase" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="Omega" ContID="Phase" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="Psi" ContID="Phase" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="SO2" ContID="Phase" Color="#408000" Informational="False">
      <Points NumItems="1">388,698</Points>
     </Link>
     <Link ElementID="F0" ContID="Phase" Color="clRed" Informational="False">
      <Points NumItems="1">365,661</Points>
     </Link>
     <Link ElementID="I" ContID="Phase" Color="clRed" Informational="False">
      <Points NumItems="2">405,64,517,64</Points>
     </Link>
     <Link ElementID="IR" ContID="Phase" Color="clRed" Informational="False">
      <Points NumItems="5">326,648,412,820,412,1340,280,1340,280,1727</Points>
     </Link>
     <Link ElementID="FIR" ContID="Phase" Color="clRed" Informational="False">
      <Points NumItems="5">338,647,422,818,422,1353,302,1354,302,1887</Points>
     </Link>
     <Link ElementID="IRt" ContID="Phase" Color="clRed" Informational="False">
      <Points NumItems="5">314,646,396,818,396,1327,260,1327,260,2065</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Var" ParentID="" ID="T" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="411" Top="73"/>
   <Parameters NumItems="4">
    <Parameter ID="Init" Indent="0">@ZeroT_DOWN+(@ZeroT_UP-@ZeroT_DOWN)*z/(NZ-1)</Parameter>
    <Parameter ID="Restrict" Indent="0">Positive</Parameter>
    <Parameter ID="FBase" Indent="0">t</Parameter>
    <Parameter ID="Desc" Indent="0">Температура</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="PhasePrm">
     <Link ElementID="MainPhase" ContID="T" Informational="False"/>
    </Contact>
    <Contact ID="Phase">
     <Link ElementID="MainPhase" ContID="Define" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqT" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="1">593,124</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Vector" ParentID="" ID="U" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="407" Top="139"/>
   <Parameters NumItems="2">
    <Parameter ID="FBase" Indent="0">v</Parameter>
    <Parameter ID="Desc" Indent="0">Скорость</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="PhasePrm">
     <Link ElementID="MainPhase" ContID="U" Informational="False"/>
     <Link ElementID="LightDustPhase" ContID="U" Informational="False"/>
    </Contact>
    <Contact ID="Phase">
     <Link ElementID="MainPhase" ContID="Define" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Vx">
     <Link ElementID="Ux" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
    <Contact ID="Vy">
     <Link ElementID="Uy" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
    <Contact ID="Vz">
     <Link ElementID="Uz" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Ux" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="589" Top="150"/>
   <Parameters NumItems="2">
    <Parameter ID="Init" Indent="0">0</Parameter>
    <Parameter ID="Restrict" Indent="0">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="U" ContID="Vx" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUxk" ContID="K" Color="#8000FF" Informational="False">
      <Points NumItems="4">686,174,686,1165,752,1180,752,1430</Points>
     </Link>
    </Contact>
    <Contact ID="Calc">
     <Link ElementID="EqUx" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="1">742,184</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Uy" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="588" Top="208"/>
   <Parameters NumItems="2">
    <Parameter ID="Init" Indent="0">0</Parameter>
    <Parameter ID="Restrict" Indent="0">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="U" ContID="Vy" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUyk" ContID="K" Color="#800040" Informational="False">
      <Points NumItems="4">692,233,692,1149,766,1170,766,1524</Points>
     </Link>
    </Contact>
    <Contact ID="Calc">
     <Link ElementID="EqUy" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Uz" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="586" Top="269"/>
   <Parameters NumItems="2">
    <Parameter ID="Init" Indent="0">0</Parameter>
    <Parameter ID="Restrict" Indent="0">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="U" ContID="Vz" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqUz" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_DynEquation" ParentID="" ID="EqT" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="889" Top="97"/>
   <Parameters NumItems="3">
    <Parameter ID="Handler" Indent="0">NULL</Parameter>
    <Parameter ID="NuMol" Indent="0">@DT</Parameter>
    <Parameter ID="Kappa" Indent="0">0.0</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="T" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_T" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="Bound">
     <Link ElementID="B_T" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Solver">
     <Link ElementID="Solver" ContID="Eqtn" Color="clBlack" Informational="False">
      <Points NumItems="1">1015,209</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Solver" ParentID="" ID="Solver" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="1202" Top="259"/>
   <Parameters NumItems="1">
    <Parameter ID="Functions" Indent="0">double GetXY(double D, double RR)
{
 double D2 = D*D;
 double D3 = D*D2;
 double D6 = D3*D3;
 double z = pow(-80.0*D3+108.0*RR+12.0*sqrt(48.0*D6-120.0*D3*RR+81.0*RR*RR),1.0/3.0);
 return z/6.0-4.0/3.0*D2/z-D/3.0;
}

double CD(double Re)
{
 if (Re&lt;0.001) return CD(0.001);
 else if (Re&lt;0.1) return 24.0/Re;
 else if (Re&lt;1.0) return 24.0/Re*(1.0+3.0/16.0*Re+9.0/160.0*Re*Re*log(2*Re));
 else if (Re&lt;900.0) return 24.0/Re*(1+0.15*pow(Re,0.678));
 else return 0.44;
}

double FFk(double g, double RO, double ROK, double Sigma, double Nu, double D, double dU)
{
 double adU = fabs(dU);
 double Re = D*adU/Nu;
 double We = 0.5*RO*D*dU*dU/Sigma;

 return 3.0/8.0*CD(Re)*(1.0+2.632*We/12.0)*RO/ROK*2.0/D*adU*dU-g;
}

double GetdU(double g, double RO, double ROK, double Sigma, double Nu, double D, double Init_dU)
{
 double dx;
 double Result = Init_dU;

 do {
   double FF  = FFk(g,RO,ROK,Sigma,Nu,D,Result);
   double FF1 = FFk(g,RO,ROK,Sigma,Nu,D,Result+0.00001);
   dx = -FF/(FF1-FF)*0.00001;
   Result += 0.5*dx;
 } while (fabs(dx)&gt;=0.0001);

 return Result;
}
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Eqtn">
     <Link ElementID="EqT" ContID="Solver" Informational="False"/>
     <Link ElementID="EqNu" ContID="Solver" Informational="False"/>
     <Link ElementID="EqUx" ContID="Solver" Informational="False"/>
     <Link ElementID="EqUy" ContID="Solver" Informational="False"/>
     <Link ElementID="EqUz" ContID="Solver" Informational="False"/>
     <Link ElementID="EqPsix" ContID="Solver" Informational="False"/>
     <Link ElementID="EqPsiy" ContID="Solver" Informational="False"/>
     <Link ElementID="EqPsiz" ContID="Solver" Informational="False"/>
     <Link ElementID="EqRo" ContID="Solver" Informational="False"/>
     <Link ElementID="EqRok" ContID="Solver" Informational="False"/>
     <Link ElementID="EqNk" ContID="Solver" Informational="False"/>
     <Link ElementID="EqSO2k" ContID="Solver" Informational="False"/>
     <Link ElementID="EqUxk" ContID="Solver" Informational="False"/>
     <Link ElementID="EqUyk" ContID="Solver" Informational="False"/>
     <Link ElementID="EqUzk" ContID="Solver" Informational="False"/>
     <Link ElementID="EqF0" ContID="Solver" Informational="False"/>
     <Link ElementID="EqI" ContID="Solver" Informational="False"/>
     <Link ElementID="Eq_IR" ContID="Solver" Informational="False"/>
     <Link ElementID="Eq_FIR" ContID="Solver" Informational="False"/>
     <Link ElementID="Eq_IRt" ContID="Solver" Informational="False"/>
     <Link ElementID="EqOmegax" ContID="Solver" Informational="False"/>
     <Link ElementID="EqOmegay" ContID="Solver" Informational="False"/>
     <Link ElementID="EqOmegaz" ContID="Solver" Informational="False"/>
    </Contact>
    <Contact ID="Modify">
     <Link ElementID="EqSO2" ContID="Solver" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
  <Element ClassID="clsE_Var" ParentID="" ID="Nu" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="393" Top="0"/>
   <Parameters NumItems="4">
    <Parameter ID="Init" Indent="0">@ZeroNu{Turbulence}</Parameter>
    <Parameter ID="Restrict" Indent="0">Positive</Parameter>
    <Parameter ID="FBase" Indent="0">nu</Parameter>
    <Parameter ID="Desc" Indent="0">Турбулентная вязкость</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="PhasePrm">
     <Link ElementID="MainPhase" ContID="Nu" Informational="False"/>
     <Link ElementID="Model" ContID="Control" Informational="True"/>
    </Contact>
    <Contact ID="Phase">
     <Link ElementID="MainPhase" ContID="Define" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqNu" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="1">698,25</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_DynEquation" ParentID="" ID="EqNu" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="1077" Top="0"/>
   <Parameters NumItems="3">
    <Parameter ID="Handler" Indent="0">NULL</Parameter>
    <Parameter ID="NuMol" Indent="0">@D</Parameter>
    <Parameter ID="Kappa" Indent="0">@Kappa{Turbulence}</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="Nu" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="S">
     <Link ElementID="S_Nu" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Solver">
     <Link ElementID="Solver" ContID="Eqtn" Color="clBlack" Informational="False">
      <Points NumItems="3">1178,64,1233,96,1193,236</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Model" ParentID="" ID="Model" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="1" Top="336"/>
   <Parameters NumItems="0"/>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Carrier">
     <Link ElementID="MainPhase" ContID="Model" Color="clRed" Informational="False">
      <Points NumItems="2">160,361,160,138</Points>
     </Link>
    </Contact>
    <Contact ID="Other">
     <Link ElementID="LightDustPhase" ContID="Model" Color="clBlack" Informational="False">
      <Points NumItems="2">163,379,163,809</Points>
     </Link>
     <Link ElementID="LightDrops" ContID="Model" Color="clBlack" Informational="False">
      <Points NumItems="2">163,378,163,994</Points>
     </Link>
    </Contact>
    <Contact ID="Control">
     <Link ElementID="Nu" ContID="PhasePrm" Color="#400080" Informational="True">
      <Points NumItems="2">170,395,170,80</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="K_Ux" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="698" Top="210"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression" Indent="0">Split{0.0,dFdy(Psiz)-dFdz(Psiy)};</Parameter>
    <Parameter ID="Vars" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUx" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="K_Uy" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="722" Top="270"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression" Indent="0">Split{0.0,dFdz(Psix)-dFdx(Psiz)};</Parameter>
    <Parameter ID="Vars" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUy" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="K_Uz" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="716" Top="352"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression" Indent="0">Split{0.0,dFdx(Psiy)-dFdy(Psix)};</Parameter>
    <Parameter ID="Vars" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUz" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="S_Nu" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="965" Top="36"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars" Indent="0">double dUxdx = Split{0.0,dFdx(Ux)};
double dUydy = Split{0.0,dFdy(Uy)};
double dUzdz = Split{0.0,dFdz(Uz)};

double dUxdy = Split{0.0,dFdy(Ux)};
double dUydz = Split{0.0,dFdz(Uy)};
double dUzdx = Split{0.0,dFdx(Uz)};

double dUxdz = Split{0.0,dFdz(Ux)};
double dUydx = Split{0.0,dFdx(Uy)};
double dUzdy = Split{0.0,dFdy(Uz)};

double FzArg  = Nu/(8*@D);
double FzArg2 = FzArg*FzArg;
double Fz     = 0.2*(FzArg2+1.47*FzArg+0.2)/(FzArg2-1.47*FzArg+1);
</Parameter>
    <Parameter ID="Expression" Indent="0">Result = Split{0.0,-@Gamma{Turbulence}*(@D+@Betta{Turbulence}*Nu)/Lmin2+
        Fz*
        sqrt(2*(dUxdx*dUxdx+dUydy*dUydy+dUzdz*dUzdz)+
               (dUxdy+dUydx)*(dUxdy+dUydx)+
               (dUxdz+dUzdx)*(dUxdz+dUzdx)+
               (dUydz+dUzdy)*(dUydz+dUzdy)
            )};
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqNu" ContID="S" Color="#8080FF" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_DirectEquation" ParentID="" ID="EqUx" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="780" Top="171"/>
   <Parameters NumItems="1">
    <Parameter ID="Handler" Indent="0">DirectSolver</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="Ux" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_Ux" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Solver">
     <Link ElementID="Solver" ContID="Eqtn" Color="clBlack" Informational="False">
      <Points NumItems="1">1018,230</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_DirectEquation" ParentID="" ID="EqUy" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="902" Top="235"/>
   <Parameters NumItems="1">
    <Parameter ID="Handler" Indent="0">DirectSolver</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="Uy" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_Uy" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Solver">
     <Link ElementID="Solver" ContID="Eqtn" Color="clBlack" Informational="False">
      <Points NumItems="1">1093,256</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_DirectEquation" ParentID="" ID="EqUz" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="806" Top="305"/>
   <Parameters NumItems="1">
    <Parameter ID="Handler" Indent="0">DirectSolver</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="Uz" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_Uz" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Solver">
     <Link ElementID="Solver" ContID="Eqtn" Color="clBlack" Informational="False">
      <Points NumItems="2">1025,311,1097,271</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Vector" ParentID="" ID="Omega" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="397" Top="313"/>
   <Parameters NumItems="2">
    <Parameter ID="FBase" Indent="0">om</Parameter>
    <Parameter ID="Desc" Indent="0">Вектор вихря</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase">
     <Link ElementID="MainPhase" ContID="Define" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Vx">
     <Link ElementID="Omegax" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
    <Contact ID="Vy">
     <Link ElementID="Omegay" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
    <Contact ID="Vz">
     <Link ElementID="Omegaz" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Omegax" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="588" Top="363"/>
   <Parameters NumItems="2">
    <Parameter ID="Init" Indent="0">0</Parameter>
    <Parameter ID="Restrict" Indent="0">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="Omega" ContID="Vx" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqOmegax" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Omegay" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="590" Top="426"/>
   <Parameters NumItems="2">
    <Parameter ID="Init" Indent="0">0</Parameter>
    <Parameter ID="Restrict" Indent="0">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="Omega" ContID="Vy" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqOmegay" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="1">789,467</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Omegaz" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="582" Top="558"/>
   <Parameters NumItems="2">
    <Parameter ID="Init" Indent="0">0</Parameter>
    <Parameter ID="Restrict" Indent="0">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="Omega" ContID="Vz" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqOmegaz" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="1">697,591</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Vector" ParentID="" ID="Psi" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="402" Top="538"/>
   <Parameters NumItems="2">
    <Parameter ID="FBase" Indent="0">psi</Parameter>
    <Parameter ID="Desc" Indent="0">Векторный потенциал</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase">
     <Link ElementID="MainPhase" ContID="Define" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Vx">
     <Link ElementID="Psix" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
    <Contact ID="Vy">
     <Link ElementID="Psiy" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
    <Contact ID="Vz">
     <Link ElementID="Psiz" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Psix" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="584" Top="637"/>
   <Parameters NumItems="2">
    <Parameter ID="Init" Indent="0">0</Parameter>
    <Parameter ID="Restrict" Indent="0">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="Psi" ContID="Vx" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">