<?xml version="1.0" encoding="windows-1251"?>
<!DOCTYPE System [
<!ELEMENT System (Elements)>
<!ATTLIST System
Lang CDATA #REQUIRED
>
<!ELEMENT Elements (Element*)>
<!ATTLIST Elements
NumItems CDATA #REQUIRED
>
<!ELEMENT Element (Show,Position,Parameters,InternalInputs,InternalOutputs,PublishedInputs,PublishedOutputs,InputLinks,OutputLinks)>
<!ATTLIST Element
ClassID CDATA #REQUIRED
ParentID CDATA #REQUIRED
ID ID #REQUIRED
Permanent (True | False) #REQUIRED
>
<!ELEMENT Show EMPTY>
<!ATTLIST Show
Class (True | False) #REQUIRED
Name (True | False) #REQUIRED
Image (True | False) #REQUIRED
>
<!ELEMENT Position EMPTY>
<!ATTLIST Position
Left CDATA #REQUIRED
Top CDATA #REQUIRED
>
<!ELEMENT Parameters (Parameter*)>
<!ATTLIST Parameters
NumItems CDATA #REQUIRED
>
<!ELEMENT Parameter (#PCDATA | EMPTY)*>
<!ATTLIST Parameter
ID CDATA #REQUIRED
>
<!ELEMENT InternalInputs (iContact*)>
<!ATTLIST InternalInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT InternalOutputs (iContact*)>
<!ATTLIST InternalOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT iContact EMPTY>
<!ATTLIST iContact
ID CDATA #REQUIRED
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
>
<!ELEMENT PublishedInputs (pContact*)>
<!ATTLIST PublishedInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT PublishedOutputs (pContact*)>
<!ATTLIST PublishedOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT pContact EMPTY>
<!ATTLIST pContact
ID CDATA #REQUIRED
PublicID CDATA #REQUIRED
PublicName CDATA #REQUIRED
>
<!ELEMENT InputLinks (Contact*)>
<!ELEMENT OutputLinks (Contact*)>
<!ELEMENT Contact (Link*)>
<!ATTLIST Contact
ID CDATA #REQUIRED
>
<!ELEMENT Link (Points?)>
<!ATTLIST Link
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
Color CDATA #IMPLIED
Informational (True | False) #REQUIRED
>
<!ELEMENT Points (#PCDATA | EMPTY)*>
<!ATTLIST Points
NumItems CDATA #REQUIRED
>
]>
<System Lang="">
 <Elements NumItems="7">
  <Element ID="X" ClassID="clsI_Value" ParentID="" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="22" Top="158"/>
   <Parameters NumItems="5">
    <Parameter ID="MLab"></Parameter>
    <Parameter ID="MLabDir"></Parameter>
    <Parameter ID="MLabFuns"></Parameter>
    <Parameter ID="Inp">LOAD(:,1)&apos;</Parameter>
    <Parameter ID="Init">global LOAD;
if exist(&apos;LOAD&apos;)==1;
   LOAD = load(&apos;water_ir_far.dat&apos;);
end;
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem102" ContID="X" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="NewItem101" ContID="X" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="NewItem7" ContID="X" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="NewItem70" ContID="X" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="NewItem19" ClassID="clsI_Dest" ParentID="" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="477" Top="194"/>
   <Parameters NumItems="5">
    <Parameter ID="MLab"></Parameter>
    <Parameter ID="MLabDir"></Parameter>
    <Parameter ID="MLabFuns"></Parameter>
    <Parameter ID="Out">LOAD(:,2)&apos;</Parameter>
    <Parameter ID="Init">global LOAD;
if exist(&apos;LOAD&apos;)==1;
   LOAD = load(&apos;water_ir_far.dat&apos;);
end;
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Y">
     <Link ElementID="NewItem102" ContID="Val" Informational="False"/>
     <Link ElementID="NewItem8" ContID="Val" Informational="False"/>
     <Link ElementID="NewItem70" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
  <Element ID="NewItem101" ClassID="clsI_UnaryNetwork" ParentID="" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="176" Top="168"/>
   <Parameters NumItems="17">
    <Parameter ID="MLab"></Parameter>
    <Parameter ID="MLabDir"></Parameter>
    <Parameter ID="MLabFuns"></Parameter>
    <Parameter ID="Inp"></Parameter>
    <Parameter ID="Res"></Parameter>
    <Parameter ID="Initialization"></Parameter>
    <Parameter ID="Goal"></Parameter>
    <Parameter ID="K"></Parameter>
    <Parameter ID="Selected"></Parameter>
    <Parameter ID="Stack"></Parameter>
    <Parameter ID="Epochs">150</Parameter>
    <Parameter ID="Rad">0</Parameter>
    <Parameter ID="NP">10</Parameter>
    <Parameter ID="Init">network</Parameter>
    <Parameter ID="Function">newff(minmax(X),[20 3 1],{&apos;tansig&apos; &apos;tansig&apos; &apos;purelin&apos;})</Parameter>
    <Parameter ID="Stopped">true</Parameter>
    <Parameter ID="R2Norm">1E30</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="X">
     <Link ElementID="X" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem8" ContID="X2" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="NewItem102" ClassID="clsI_UnaryNetwork" ParentID="" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="174" Top="235"/>
   <Parameters NumItems="17">
    <Parameter ID="MLab"></Parameter>
    <Parameter ID="MLabDir"></Parameter>
    <Parameter ID="MLabFuns"></Parameter>
    <Parameter ID="Inp"></Parameter>
    <Parameter ID="Res"></Parameter>
    <Parameter ID="Initialization"></Parameter>
    <Parameter ID="Goal"></Parameter>
    <Parameter ID="K"></Parameter>
    <Parameter ID="Selected"></Parameter>
    <Parameter ID="Stack"></Parameter>
    <Parameter ID="Epochs">150</Parameter>
    <Parameter ID="Rad">0</Parameter>
    <Parameter ID="NP">10</Parameter>
    <Parameter ID="Init">network</Parameter>
    <Parameter ID="Function">newff(minmax(X),[$Ncommon 3 1],{&apos;tansig&apos; &apos;tansig&apos; &apos;purelin&apos;})</Parameter>
    <Parameter ID="Stopped">true</Parameter>
    <Parameter ID="R2Norm">1E30</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="X">
     <Link ElementID="X" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem19" ContID="Y" Color="clBlack" Informational="False">
      <Points NumItems="1">366,260</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="NewItem8" ClassID="clsI_BinaryFunction" ParentID="" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="332" Top="135"/>
   <Parameters NumItems="23">
    <Parameter ID="MLab"></Parameter>
    <Parameter ID="MLabDir"></Parameter>
    <Parameter ID="MLabFuns"></Parameter>
    <Parameter ID="Inp1"></Parameter>
    <Parameter ID="Inp2"></Parameter>
    <Parameter ID="Res"></Parameter>
    <Parameter ID="Initialization"></Parameter>
    <Parameter ID="Goal"></Parameter>
    <Parameter ID="K"></Parameter>
    <Parameter ID="Selected"></Parameter>
    <Parameter ID="State"></Parameter>
    <Parameter ID="Stack"></Parameter>
    <Parameter ID="Fix"></Parameter>
    <Parameter ID="Rad">[]</Parameter>
    <Parameter ID="NP">3</Parameter>
    <Parameter ID="RevF2">Y./X1</Parameter>
    <Parameter ID="RevF1">Y./X2</Parameter>
    <Parameter ID="VarX">X2</Parameter>
    <Parameter ID="Init">[]</Parameter>
    <Parameter ID="Function">X1.*X2</Parameter>
    <Parameter ID="Stopped">true</Parameter>
    <Parameter ID="R2Norm">1E30</Parameter>
    <Parameter ID="Recalc">true</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="X2">
     <Link ElementID="NewItem101" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="X1">
     <Link ElementID="NewItem7" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem19" ContID="Y" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="NewItem7" ClassID="clsI_UnaryPoly" ParentID="" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="176" Top="110"/>
   <Parameters NumItems="17">
    <Parameter ID="MLab"></Parameter>
    <Parameter ID="MLabDir"></Parameter>
    <Parameter ID="MLabFuns"></Parameter>
    <Parameter ID="Inp"></Parameter>
    <Parameter ID="Res"></Parameter>
    <Parameter ID="Initialization"></Parameter>
    <Parameter ID="Goal"></Parameter>
    <Parameter ID="K"></Parameter>
    <Parameter ID="Selected"></Parameter>
    <Parameter ID="Stack"></Parameter>
    <Parameter ID="PolyN">7</Parameter>
    <Parameter ID="Rad">0</Parameter>
    <Parameter ID="NP">1</Parameter>
    <Parameter ID="Init">polynom</Parameter>
    <Parameter ID="Function">polyval(K,X)</Parameter>
    <Parameter ID="Stopped">true</Parameter>
    <Parameter ID="R2Norm">1E30</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="X">
     <Link ElementID="X" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem8" ContID="X1" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="NewItem70" ClassID="clsI_UnaryPoly" ParentID="" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="176" Top="298"/>
   <Parameters NumItems="17">
    <Parameter ID="MLab"></Parameter>
    <Parameter ID="MLabDir"></Parameter>
    <Parameter ID="MLabFuns"></Parameter>
    <Parameter ID="Inp"></Parameter>
    <Parameter ID="Res"></Parameter>
    <Parameter ID="Initialization"></Parameter>
    <Parameter ID="Goal"></Parameter>
    <Parameter ID="K"></Parameter>
    <Parameter ID="Selected"></Parameter>
    <Parameter ID="Stack"></Parameter>
    <Parameter ID="PolyN">16</Parameter>
    <Parameter ID="Rad">0</Parameter>
    <Parameter ID="NP">1</Parameter>
    <Parameter ID="Init">polynom</Parameter>
    <Parameter ID="Function">polyval(K,X)</Parameter>
    <Parameter ID="Stopped">true</Parameter>
    <Parameter ID="R2Norm">1E30</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="X">
     <Link ElementID="X" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem19" ContID="Y" Color="clBlack" Informational="False">
      <Points NumItems="1">365,323</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
 </Elements>
</System>
