<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE System [
<!ELEMENT System (Elements)>
<!ATTLIST System
Lang CDATA #REQUIRED
>
<!ELEMENT Elements (Element*)>
<!ATTLIST Elements
NumItems CDATA #REQUIRED
>
<!ELEMENT Element (Show,Position,Parameters,InternalInputs,InternalOutputs,PublishedInputs,PublishedOutputs,InputLinks,OutputLinks)>
<!ATTLIST Element
ClassID CDATA #REQUIRED
ParentID CDATA #REQUIRED
ID ID #REQUIRED
Permanent (True | False) #REQUIRED
>
<!ELEMENT Show EMPTY>
<!ATTLIST Show
Class (True | False) #REQUIRED
Name (True | False) #REQUIRED
Image (True | False) #REQUIRED
>
<!ELEMENT Position EMPTY>
<!ATTLIST Position
Left CDATA #REQUIRED
Top CDATA #REQUIRED
>
<!ELEMENT Parameters (Parameter*)>
<!ATTLIST Parameters
NumItems CDATA #REQUIRED
>
<!ELEMENT Parameter (#PCDATA | EMPTY)*>
<!ATTLIST Parameter
ID CDATA #REQUIRED
Indent CDATA #IMPLIED
>
<!ELEMENT InternalInputs (iContact*)>
<!ATTLIST InternalInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT InternalOutputs (iContact*)>
<!ATTLIST InternalOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT iContact EMPTY>
<!ATTLIST iContact
ID CDATA #REQUIRED
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
>
<!ELEMENT PublishedInputs (pContact*)>
<!ATTLIST PublishedInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT PublishedOutputs (pContact*)>
<!ATTLIST PublishedOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT pContact EMPTY>
<!ATTLIST pContact
ID CDATA #REQUIRED
PublicID CDATA #REQUIRED
PublicName CDATA #REQUIRED
>
<!ELEMENT InputLinks (Contact*)>
<!ELEMENT OutputLinks (Contact*)>
<!ELEMENT Contact (Link*)>
<!ATTLIST Contact
ID CDATA #REQUIRED
>
<!ELEMENT Link (Points?)>
<!ATTLIST Link
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
Color CDATA #IMPLIED
Informational (True | False) #REQUIRED
>
<!ELEMENT Points (#PCDATA | EMPTY)*>
<!ATTLIST Points
NumItems CDATA #REQUIRED
>
]>
<System Lang="">
 <Elements NumItems="10">
  <Element ClassID="clsI_Value" ParentID="" ID="X" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="88" Top="123"/>
   <Parameters NumItems="5">
    <Parameter ID="Inp" Indent="0">[0.5 1.5 2.5 3.8 4.5 6 7 8]</Parameter>
    <Parameter ID="Init" Indent="0"></Parameter>
    <Parameter ID="MLab" Indent="0"></Parameter>
    <Parameter ID="MLabDir" Indent="0"></Parameter>
    <Parameter ID="MLabFuns" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem2" ContID="X" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="NewItem5" ContID="X" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="NewItem6" ContID="X" Color="clBlack" Informational="False">
      <Points NumItems="1">165,236</Points>
     </Link>
     <Link ElementID="NewItem8" ContID="X" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="NewItem9" ContID="X" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsI_UnaryFunction" ParentID="" ID="NewItem2" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="189" Top="185"/>
   <Parameters NumItems="16">
    <Parameter ID="R2Norm" Indent="0">1E30</Parameter>
    <Parameter ID="Stopped" Indent="0">true</Parameter>
    <Parameter ID="Function" Indent="0">X.*X.*K(1)+X.*K(2)+K(3)</Parameter>
    <Parameter ID="Init" Indent="0">[0 0 0]</Parameter>
    <Parameter ID="NP" Indent="0">3</Parameter>
    <Parameter ID="Rad" Indent="0">[1 1 1]</Parameter>
    <Parameter ID="Initialization" Indent="0"></Parameter>
    <Parameter ID="Goal" Indent="0"></Parameter>
    <Parameter ID="Stack" Indent="0"></Parameter>
    <Parameter ID="Selected" Indent="0"></Parameter>
    <Parameter ID="Res" Indent="0"></Parameter>
    <Parameter ID="K" Indent="0"></Parameter>
    <Parameter ID="MLab" Indent="0"></Parameter>
    <Parameter ID="MLabDir" Indent="0"></Parameter>
    <Parameter ID="MLabFuns" Indent="0"></Parameter>
    <Parameter ID="Inp" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="X">
     <Link ElementID="X" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem4" ContID="X" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsI_Dest" ParentID="" ID="NewItem3" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="528" Top="125"/>
   <Parameters NumItems="5">
    <Parameter ID="Out" Indent="0">[-0.249 -4.643 11.021 -21.917 25.52 -39.051 56.893 -77.88]</Parameter>
    <Parameter ID="Init" Indent="0"></Parameter>
    <Parameter ID="MLab" Indent="0"></Parameter>
    <Parameter ID="MLabDir" Indent="0"></Parameter>
    <Parameter ID="MLabFuns" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Y">
     <Link ElementID="NewItem4" ContID="Val" Informational="False"/>
     <Link ElementID="NewItem6" ContID="Val" Informational="False"/>
     <Link ElementID="NewItem7" ContID="Val" Informational="False"/>
     <Link ElementID="NewItem10" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
  <Element ClassID="clsI_UnaryFunction" ParentID="" ID="NewItem4" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="299" Top="140"/>
   <Parameters NumItems="16">
    <Parameter ID="R2Norm" Indent="0">1E30</Parameter>
    <Parameter ID="Stopped" Indent="0">true</Parameter>
    <Parameter ID="Function" Indent="0">X.*X.*K(1)+X.*K(2)+K(3)</Parameter>
    <Parameter ID="Init" Indent="0">[1 1 1]</Parameter>
    <Parameter ID="NP" Indent="0">3</Parameter>
    <Parameter ID="Rad" Indent="0">1.5</Parameter>
    <Parameter ID="Initialization" Indent="0"></Parameter>
    <Parameter ID="Goal" Indent="0"></Parameter>
    <Parameter ID="Stack" Indent="0"></Parameter>
    <Parameter ID="Selected" Indent="0"></Parameter>
    <Parameter ID="MLab" Indent="0"></Parameter>
    <Parameter ID="MLabDir" Indent="0"></Parameter>
    <Parameter ID="MLabFuns" Indent="0"></Parameter>
    <Parameter ID="Inp" Indent="0"></Parameter>
    <Parameter ID="Res" Indent="0"></Parameter>
    <Parameter ID="K" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="X">
     <Link ElementID="NewItem2" ContID="Val" Informational="False"/>
     <Link ElementID="NewItem5" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem3" ContID="Y" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="NewItem7" ContID="X1" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsI_UnaryFunction" ParentID="" ID="NewItem5" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="182" Top="103"/>
   <Parameters NumItems="16">
    <Parameter ID="R2Norm" Indent="0">1E30</Parameter>
    <Parameter ID="Stopped" Indent="0">true</Parameter>
    <Parameter ID="Function" Indent="0">cos(X.*K(1)+K(2))*K(3)+K(4)</Parameter>
    <Parameter ID="Init" Indent="0">[1 1 1 1]</Parameter>
    <Parameter ID="NP" Indent="0">10</Parameter>
    <Parameter ID="Rad" Indent="0">[5 5 5 5]</Parameter>
    <Parameter ID="Initialization" Indent="0"></Parameter>
    <Parameter ID="Goal" Indent="0"></Parameter>
    <Parameter ID="Stack" Indent="0"></Parameter>
    <Parameter ID="Selected" Indent="0"></Parameter>
    <Parameter ID="MLab" Indent="0"></Parameter>
    <Parameter ID="MLabDir" Indent="0"></Parameter>
    <Parameter ID="MLabFuns" Indent="0"></Parameter>
    <Parameter ID="Inp" Indent="0"></Parameter>
    <Parameter ID="Res" Indent="0"></Parameter>
    <Parameter ID="K" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="X">
     <Link ElementID="X" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem4" ContID="X" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsI_UnaryFunction" ParentID="" ID="NewItem6" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="198" Top="242"/>
   <Parameters NumItems="16">
    <Parameter ID="R2Norm" Indent="0">1E30</Parameter>
    <Parameter ID="Stopped" Indent="0">true</Parameter>
    <Parameter ID="Function" Indent="0">X.*X.*X.*X.*K(1)+X.*X.*X.*K(2)+X.*X.*K(3)+X.*K(4)+K(5)</Parameter>
    <Parameter ID="Init" Indent="0">[1 1 1 1 1]</Parameter>
    <Parameter ID="NP" Indent="0">10</Parameter>
    <Parameter ID="Rad" Indent="0">[2 2 2 2 2]</Parameter>
    <Parameter ID="Initialization" Indent="0"></Parameter>
    <Parameter ID="Goal" Indent="0"></Parameter>
    <Parameter ID="Stack" Indent="0"></Parameter>
    <Parameter ID="MLab" Indent="0"></Parameter>
    <Parameter ID="MLabDir" Indent="0"></Parameter>
    <Parameter ID="MLabFuns" Indent="0"></Parameter>
    <Parameter ID="Inp" Indent="0"></Parameter>
    <Parameter ID="Res" Indent="0"></Parameter>
    <Parameter ID="K" Indent="0"></Parameter>
    <Parameter ID="Selected" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="X">
     <Link ElementID="X" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem3" ContID="Y" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="NewItem7" ContID="X1" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsI_BinaryFunction" ParentID="" ID="NewItem7" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="465" Top="281"/>
   <Parameters NumItems="23">
    <Parameter ID="Recalc" Indent="0">true</Parameter>
    <Parameter ID="R2Norm" Indent="0">1E30</Parameter>
    <Parameter ID="Stopped" Indent="0">true</Parameter>
    <Parameter ID="Function" Indent="0">X1*K(1)+X2*K(2)</Parameter>
    <Parameter ID="Init" Indent="0">[1 1]</Parameter>
    <Parameter ID="VarX" Indent="0">Best</Parameter>
    <Parameter ID="RevF1" Indent="0">Y-X2</Parameter>
    <Parameter ID="RevF2" Indent="0">Y-X1</Parameter>
    <Parameter ID="NP" Indent="0">5</Parameter>
    <Parameter ID="Rad" Indent="0">[1 1]</Parameter>
    <Parameter ID="Initialization" Indent="0"></Parameter>
    <Parameter ID="Goal" Indent="0"></Parameter>
    <Parameter ID="Fix" Indent="0"></Parameter>
    <Parameter ID="Stack" Indent="0"></Parameter>
    <Parameter ID="State" Indent="0"></Parameter>
    <Parameter ID="Inp1" Indent="0"></Parameter>
    <Parameter ID="Inp2" Indent="0"></Parameter>
    <Parameter ID="MLab" Indent="0"></Parameter>
    <Parameter ID="MLabDir" Indent="0"></Parameter>
    <Parameter ID="MLabFuns" Indent="0"></Parameter>
    <Parameter ID="Res" Indent="0"></Parameter>
    <Parameter ID="K" Indent="0"></Parameter>
    <Parameter ID="Selected" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="X1">
     <Link ElementID="NewItem4" ContID="Val" Informational="False"/>
     <Link ElementID="NewItem6" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="X2">
     <Link ElementID="NewItem10" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem3" ContID="Y" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsI_UnaryFunction" ParentID="" ID="NewItem8" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="202" Top="297"/>
   <Parameters NumItems="16">
    <Parameter ID="R2Norm" Indent="0">1E30</Parameter>
    <Parameter ID="Stopped" Indent="0">true</Parameter>
    <Parameter ID="Function" Indent="0">X.*X.*K(1)+X.*K(2)+K(3)</Parameter>
    <Parameter ID="Init" Indent="0">[1 1 1]</Parameter>
    <Parameter ID="NP" Indent="0">3</Parameter>
    <Parameter ID="Rad" Indent="0">[1 1 1]</Parameter>
    <Parameter ID="Initialization" Indent="0"></Parameter>
    <Parameter ID="Goal" Indent="0"></Parameter>
    <Parameter ID="Stack" Indent="0"></Parameter>
    <Parameter ID="MLab" Indent="0"></Parameter>
    <Parameter ID="MLabDir" Indent="0"></Parameter>
    <Parameter ID="MLabFuns" Indent="0"></Parameter>
    <Parameter ID="Inp" Indent="0"></Parameter>
    <Parameter ID="Res" Indent="0"></Parameter>
    <Parameter ID="K" Indent="0"></Parameter>
    <Parameter ID="Selected" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="X">
     <Link ElementID="X" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem10" ContID="X1" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsI_UnaryFunction" ParentID="" ID="NewItem9" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="200" Top="354"/>
   <Parameters NumItems="16">
    <Parameter ID="R2Norm" Indent="0">1E30</Parameter>
    <Parameter ID="Stopped" Indent="0">true</Parameter>
    <Parameter ID="Function" Indent="0">sin(X.*K(1)+K(2))*K(3)</Parameter>
    <Parameter ID="Init" Indent="0">[3 0 30]</Parameter>
    <Parameter ID="NP" Indent="0">3</Parameter>
    <Parameter ID="Rad" Indent="0">[1 1 1]</Parameter>
    <Parameter ID="Initialization" Indent="0"></Parameter>
    <Parameter ID="Goal" Indent="0"></Parameter>
    <Parameter ID="Stack" Indent="0"></Parameter>
    <Parameter ID="MLab" Indent="0"></Parameter>
    <Parameter ID="MLabDir" Indent="0"></Parameter>
    <Parameter ID="MLabFuns" Indent="0"></Parameter>
    <Parameter ID="Inp" Indent="0"></Parameter>
    <Parameter ID="Res" Indent="0"></Parameter>
    <Parameter ID="K" Indent="0"></Parameter>
    <Parameter ID="Selected" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="X">
     <Link ElementID="X" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem10" ContID="X2" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsI_BinaryFunction" ParentID="" ID="NewItem10" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="310" Top="312"/>
   <Parameters NumItems="23">
    <Parameter ID="Recalc" Indent="0">true</Parameter>
    <Parameter ID="R2Norm" Indent="0">1E30</Parameter>
    <Parameter ID="Stopped" Indent="0">true</Parameter>
    <Parameter ID="Function" Indent="0">X1.*X2</Parameter>
    <Parameter ID="Init" Indent="0">[]</Parameter>
    <Parameter ID="VarX" Indent="0">X1</Parameter>
    <Parameter ID="RevF1" Indent="0">Y./X2</Parameter>
    <Parameter ID="RevF2" Indent="0">Y./X1</Parameter>
    <Parameter ID="NP" Indent="0">5</Parameter>
    <Parameter ID="Rad" Indent="0">[]</Parameter>
    <Parameter ID="Initialization" Indent="0"></Parameter>
    <Parameter ID="Goal" Indent="0"></Parameter>
    <Parameter ID="Fix" Indent="0"></Parameter>
    <Parameter ID="Stack" Indent="0"></Parameter>
    <Parameter ID="State" Indent="0"></Parameter>
    <Parameter ID="MLab" Indent="0"></Parameter>
    <Parameter ID="MLabDir" Indent="0"></Parameter>
    <Parameter ID="MLabFuns" Indent="0"></Parameter>
    <Parameter ID="Inp1" Indent="0"></Parameter>
    <Parameter ID="Inp2" Indent="0"></Parameter>
    <Parameter ID="Res" Indent="0"></Parameter>
    <Parameter ID="K" Indent="0"></Parameter>
    <Parameter ID="Selected" Indent="0"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="X1">
     <Link ElementID="NewItem8" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="X2">
     <Link ElementID="NewItem9" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="NewItem3" ContID="Y" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="NewItem7" ContID="X2" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
 </Elements>
</System>
