<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE System [
<!ELEMENT System (Elements)>
<!ATTLIST System
Lang CDATA #REQUIRED
>
<!ELEMENT Elements (Element*)>
<!ATTLIST Elements
NumItems CDATA #REQUIRED
>
<!ELEMENT Element (Show,Position,Parameters,InternalInputs,InternalOutputs,PublishedInputs,PublishedOutputs,InputLinks,OutputLinks)>
<!ATTLIST Element
ClassID CDATA #REQUIRED
ParentID CDATA #REQUIRED
ID ID #REQUIRED
Permanent (True | False) #REQUIRED
>
<!ELEMENT Show EMPTY>
<!ATTLIST Show
Class (True | False) #REQUIRED
Name (True | False) #REQUIRED
Image (True | False) #REQUIRED
>
<!ELEMENT Position EMPTY>
<!ATTLIST Position
Left CDATA #REQUIRED
Top CDATA #REQUIRED
>
<!ELEMENT Parameters (Parameter*)>
<!ATTLIST Parameters
NumItems CDATA #REQUIRED
>
<!ELEMENT Parameter (#PCDATA | EMPTY)*>
<!ATTLIST Parameter
ID CDATA #REQUIRED
Indent CDATA #IMPLIED
>
<!ELEMENT InternalInputs (iContact*)>
<!ATTLIST InternalInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT InternalOutputs (iContact*)>
<!ATTLIST InternalOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT iContact EMPTY>
<!ATTLIST iContact
ID CDATA #REQUIRED
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
>
<!ELEMENT PublishedInputs (pContact*)>
<!ATTLIST PublishedInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT PublishedOutputs (pContact*)>
<!ATTLIST PublishedOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT pContact EMPTY>
<!ATTLIST pContact
ID CDATA #REQUIRED
PublicID CDATA #REQUIRED
PublicName CDATA #REQUIRED
>
<!ELEMENT InputLinks (Contact*)>
<!ELEMENT OutputLinks (Contact*)>
<!ELEMENT Contact (Link*)>
<!ATTLIST Contact
ID CDATA #REQUIRED
>
<!ELEMENT Link (Points?)>
<!ATTLIST Link
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
Color CDATA #IMPLIED
Informational (True | False) #REQUIRED
>
<!ELEMENT Points (#PCDATA | EMPTY)*>
<!ATTLIST Points
NumItems CDATA #REQUIRED
>
]>
<System Lang="">
 <Elements NumItems="8">
  <Element ClassID="clsSimpleScalar" ParentID="" ID="max" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="50" Top="50"/>
   <Parameters NumItems="1">
    <Parameter ID="ID" Indent="0">max</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Asgn">
     <Link ElementID="MaxVmax" ContID="Res" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Handle">
     <Link ElementID="outmax" ContID="Arg" Color="#000000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsSimpleVector" ParentID="" ID="V" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="170" Top="50"/>
   <Parameters NumItems="2">
    <Parameter ID="ID" Indent="0">V</Parameter>
    <Parameter ID="Size" Indent="0">10</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Handle">
     <Link ElementID="MaxVmax" ContID="Arg" Color="#000000" Informational="False">
      <Points NumItems="0"/>
     </Link>
     <Link ElementID="inV" ContID="Arg" Color="#000000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsSimpleMat" ParentID="" ID="MaxVmax" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="290" Top="50"/>
   <Parameters NumItems="3">
    <Parameter ID="IVar" Indent="0">V</Parameter>
    <Parameter ID="Op" Indent="0">Max</Parameter>
    <Parameter ID="OVar" Indent="0">max</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Arg">
     <Link ElementID="V" ContID="Handle" Informational="False"/>
    </Contact>
    <Contact ID="Prev">
     <Link ElementID="inV" ContID="Next" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Next">
     <Link ElementID="outmax" ContID="Prev" Color="#000000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
    <Contact ID="Res">
     <Link ElementID="max" ContID="Asgn" Color="#000000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsSimpleInput" ParentID="" ID="inV" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="410" Top="50"/>
   <Parameters NumItems="1">
    <Parameter ID="IVar" Indent="0">V</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Arg">
     <Link ElementID="V" ContID="Handle" Informational="False"/>
    </Contact>
    <Contact ID="Prev">
     <Link ElementID="PROG" ContID="Begin" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Next">
     <Link ElementID="MaxVmax" ContID="Prev" Color="#000000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsSimpleOut" ParentID="" ID="outmax" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="530" Top="50"/>
   <Parameters NumItems="1">
    <Parameter ID="IVar" Indent="0">max</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Arg">
     <Link ElementID="max" ContID="Handle" Informational="False"/>
    </Contact>
    <Contact ID="Prev">
     <Link ElementID="MaxVmax" ContID="Next" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Next">
     <Link ElementID="END" ContID="End" Color="#000000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsSimpleTerminator" ParentID="" ID="END" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="650" Top="50"/>
   <Parameters NumItems="0"/>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="End">
     <Link ElementID="outmax" ContID="Next" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
  <Element ClassID="clsSimpleTest" ParentID="" ID="vhjfqota" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="770" Top="50"/>
   <Parameters NumItems="2">
    <Parameter ID="Input" Indent="0">1 2 3 4 5 6 7 8 9 10</Parameter>
    <Parameter ID="Output" Indent="0">V[0] = V[1] = V[2] = V[3] = V[4] = V[5] = V[6] = V[7] = V[8] = V[9] = max = 10.000000</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks/>
  </Element>
  <Element ClassID="clsSimpleProgram" ParentID="" ID="PROG" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="890" Top="50"/>
   <Parameters NumItems="1">
    <Parameter ID="Name" Indent="0">PROGRAM</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Begin">
     <Link ElementID="inV" ContID="Prev" Color="#000000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
 </Elements>
</System>
