<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE System [
<!ELEMENT System (Elements)>
<!ATTLIST System
Lang CDATA #REQUIRED
>
<!ELEMENT Elements (Element*)>
<!ATTLIST Elements
NumItems CDATA #REQUIRED
>
<!ELEMENT Element (Show,Position,Parameters,InternalInputs,InternalOutputs,PublishedInputs,PublishedOutputs,InputLinks,OutputLinks)>
<!ATTLIST Element
ClassID CDATA #REQUIRED
ParentID CDATA #REQUIRED
ID ID #REQUIRED
Permanent (True | False) #REQUIRED
>
<!ELEMENT Show EMPTY>
<!ATTLIST Show
Class (True | False) #REQUIRED
Name (True | False) #REQUIRED
Image (True | False) #REQUIRED
>
<!ELEMENT Position EMPTY>
<!ATTLIST Position
Left CDATA #REQUIRED
Top CDATA #REQUIRED
>
<!ELEMENT Parameters (Parameter*)>
<!ATTLIST Parameters
NumItems CDATA #REQUIRED
>
<!ELEMENT Parameter (#PCDATA | EMPTY)*>
<!ATTLIST Parameter
ID CDATA #REQUIRED
>
<!ELEMENT InternalInputs (iContact*)>
<!ATTLIST InternalInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT InternalOutputs (iContact*)>
<!ATTLIST InternalOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT iContact EMPTY>
<!ATTLIST iContact
ID CDATA #REQUIRED
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
>
<!ELEMENT PublishedInputs (pContact*)>
<!ATTLIST PublishedInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT PublishedOutputs (pContact*)>
<!ATTLIST PublishedOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT pContact EMPTY>
<!ATTLIST pContact
ID CDATA #REQUIRED
PublicID CDATA #REQUIRED
PublicName CDATA #REQUIRED
>
<!ELEMENT InputLinks (Contact*)>
<!ELEMENT OutputLinks (Contact*)>
<!ELEMENT Contact (Link*)>
<!ATTLIST Contact
ID CDATA #REQUIRED
>
<!ELEMENT Link (Points?)>
<!ATTLIST Link
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
Color CDATA #IMPLIED
Informational (True | False) #REQUIRED
>
<!ELEMENT Points (#PCDATA | EMPTY)*>
<!ATTLIST Points
NumItems CDATA #REQUIRED
>
]>
<System Lang="">
 <Elements NumItems="26">
  <Element ClassID="clsE_Vector" ParentID="" ID="U" Permanent="True">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="407" Top="139"/>
   <Parameters NumItems="2">
    <Parameter ID="FBase">v</Parameter>
    <Parameter ID="Desc">Скорость</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="2">
     <pContact ID="PhasePrm" PublicID="PrmU" PublicName="Скорость"/>
     <pContact ID="Phase" PublicID="PhaseU" PublicName="Фаза (U)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Vx">
     <Link ElementID="Ux" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
    <Contact ID="Vy">
     <Link ElementID="Uy" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
    <Contact ID="Vz">
     <Link ElementID="Uz" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Ux" Permanent="True">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="589" Top="150"/>
   <Parameters NumItems="2">
    <Parameter ID="Init">0</Parameter>
    <Parameter ID="Restrict">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="U" ContID="Vx" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqUx" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="1">710,141</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Uy" Permanent="True">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="588" Top="208"/>
   <Parameters NumItems="2">
    <Parameter ID="Init">0</Parameter>
    <Parameter ID="Restrict">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="U" ContID="Vy" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqUy" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Uz" Permanent="True">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="586" Top="269"/>
   <Parameters NumItems="2">
    <Parameter ID="Init">0</Parameter>
    <Parameter ID="Restrict">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="U" ContID="Vz" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqUz" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="K_Ux" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="714" Top="166"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars">double dWxdx = Split{0.0,dFdx(Omegax)};
double dWydy = Split{0.0,dFdy(Omegay)};
double dWzdz = Split{0.0,dFdz(Omegaz)};

double dWxdy = Split{0.0,dFdy(Omegax)};
double dWydz = Split{0.0,dFdz(Omegay)};
double dWzdx = Split{0.0,dFdx(Omegaz)};

double dWxdz = Split{0.0,dFdz(Omegax)};
double dWydx = Split{0.0,dFdx(Omegay)};
double dWzdy = Split{0.0,dFdy(Omegaz)};
</Parameter>
    <Parameter ID="Expression">Split{0.0,dWzdy-dWydz};</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUx" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="K_Uy" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="714" Top="257"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars">double dWxdx = Split{0.0,dFdx(Omegax)};
double dWydy = Split{0.0,dFdy(Omegay)};
double dWzdz = Split{0.0,dFdz(Omegaz)};

double dWxdy = Split{0.0,dFdy(Omegax)};
double dWydz = Split{0.0,dFdz(Omegay)};
double dWzdx = Split{0.0,dFdx(Omegaz)};

double dWxdz = Split{0.0,dFdz(Omegax)};
double dWydx = Split{0.0,dFdx(Omegay)};
double dWzdy = Split{0.0,dFdy(Omegaz)};
</Parameter>
    <Parameter ID="Expression">Split{0.0,dWxdz-dWzdx};</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUy" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="K_Uz" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="704" Top="346"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars">double dWxdx = Split{0.0,dFdx(Omegax)};
double dWydy = Split{0.0,dFdy(Omegay)};
double dWzdz = Split{0.0,dFdz(Omegaz)};

double dWxdy = Split{0.0,dFdy(Omegax)};
double dWydz = Split{0.0,dFdz(Omegay)};
double dWzdx = Split{0.0,dFdx(Omegaz)};

double dWxdz = Split{0.0,dFdz(Omegax)};
double dWydx = Split{0.0,dFdx(Omegay)};
double dWzdy = Split{0.0,dFdy(Omegaz)};
</Parameter>
    <Parameter ID="Expression">Split{0.0,dWydx-dWxdy};</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUz" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Vector" ParentID="" ID="Omega" Permanent="True">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="397" Top="313"/>
   <Parameters NumItems="2">
    <Parameter ID="FBase">om</Parameter>
    <Parameter ID="Desc">Вектор вихря</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="1">
     <pContact ID="Phase" PublicID="PhaseOmega" PublicName="Фаза (Omega)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Vx">
     <Link ElementID="Omegax" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
    <Contact ID="Vy">
     <Link ElementID="Omegay" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
    <Contact ID="Vz">
     <Link ElementID="Omegaz" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Omegax" Permanent="True">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="588" Top="363"/>
   <Parameters NumItems="2">
    <Parameter ID="Init">0</Parameter>
    <Parameter ID="Restrict">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="Omega" ContID="Vx" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqOmegax" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="1">884,405</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Omegay" Permanent="True">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="590" Top="426"/>
   <Parameters NumItems="2">
    <Parameter ID="Init">0</Parameter>
    <Parameter ID="Restrict">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="Omega" ContID="Vy" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqOmegay" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Omegaz" Permanent="True">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="582" Top="558"/>
   <Parameters NumItems="2">
    <Parameter ID="Init">0</Parameter>
    <Parameter ID="Restrict">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="Omega" ContID="Vz" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqOmegaz" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="3">701,593,791,593,821,575</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="K_Omegax" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="735" Top="410"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars">double dUxdx = Split{0.0,dFdx(Ux)};
double dUydy = Split{0.0,dFdy(Uy)};
double dUzdz = Split{0.0,dFdz(Uz)};

double dUxdy = Split{0.0,dFdy(Ux)};
double dUydz = Split{0.0,dFdz(Uy)};
double dUzdx = Split{0.0,dFdx(Uz)};

double dUxdz = Split{0.0,dFdz(Ux)};
double dUydx = Split{0.0,dFdx(Uy)};
double dUzdy = Split{0.0,dFdy(Uz)};
</Parameter>
    <Parameter ID="Expression">Split{0.0,Omegay*dUxdy+Omegaz*dUxdz+(dRdFdx2(Omegax,Nu)+dRdFdy2(Omegax,Nu)+dRdFdz2(Omegax,Nu))};</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqOmegax" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="2">824,417,874,417</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="K_Omegay" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="611" Top="482"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars">double dUxdx = Split{0.0,dFdx(Ux)};
double dUydy = Split{0.0,dFdy(Uy)};
double dUzdz = Split{0.0,dFdz(Uz)};

double dUxdy = Split{0.0,dFdy(Ux)};
double dUydz = Split{0.0,dFdz(Uy)};
double dUzdx = Split{0.0,dFdx(Uz)};

double dUxdz = Split{0.0,dFdz(Ux)};
double dUydx = Split{0.0,dFdx(Uy)};
double dUzdy = Split{0.0,dFdy(Uz)};
</Parameter>
    <Parameter ID="Expression">Split{0.0,Omegax*dUydx+Omegaz*dUydz+(dRdFdx2(Omegay,Nu)+dRdFdy2(Omegay,Nu)+dRdFdz2(Omegay,Nu))};</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqOmegay" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="2">743,497,793,497</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="K_Omegaz" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="717" Top="600"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars">double dUxdx = Split{0.0,dFdx(Ux)};
double dUydy = Split{0.0,dFdy(Uy)};
double dUzdz = Split{0.0,dFdz(Uz)};

double dUxdy = Split{0.0,dFdy(Ux)};
double dUydz = Split{0.0,dFdz(Uy)};
double dUzdx = Split{0.0,dFdx(Uz)};

double dUxdz = Split{0.0,dFdz(Ux)};
double dUydx = Split{0.0,dFdx(Uy)};
double dUzdy = Split{0.0,dFdy(Uz)};
</Parameter>
    <Parameter ID="Expression">Split{0.0,Omegax*dUzdx+Omegay*dUzdy+(dRdFdx2(Omegaz,Nu)+dRdFdy2(Omegaz,Nu)+dRdFdz2(Omegaz,Nu))};</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqOmegaz" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="1">813,591</Points>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="B_Omegax" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="828" Top="426"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars">double dUxdx = Split{0.0,dFdx(Ux)};
double dUydy = Split{0.0,dFdy(Uy)};
double dUzdz = Split{0.0,dFdz(Uz)};

double dUxdy = Split{0.0,dFdy(Ux)};
double dUydz = Split{0.0,dFdz(Uy)};
double dUzdx = Split{0.0,dFdx(Uz)};

double dUxdz = Split{0.0,dFdz(Ux)};
double dUydx = Split{0.0,dFdx(Uy)};
double dUzdy = Split{0.0,dFdy(Uz)};
</Parameter>
    <Parameter ID="Expression">Result = IsCond(Omegax,A) ?
                                   IsForw ? +2.0*(-Uz[back]+Uz)/HY[YM]-Omegax[back] :
                                   IsBack ? -2.0*(-Uz[forw]+Uz)/HY[y]-Omegax[forw] :
                                   IsBottom ? +2.0*(-Uy[up]+Uy)/HZ[z]-Omegax[up] :
                                   IsTop ? -2.0*(-Uy[down]+Uy)/HZ_ZM-Omegax[down] :
                                   0.0 : dUzdy-dUydz;
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqOmegax" ContID="Bound" Color="#FF0080" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="B_Omegay" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="731" Top="510"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars">double dUxdx = Split{0.0,dFdx(Ux)};
double dUydy = Split{0.0,dFdy(Uy)};
double dUzdz = Split{0.0,dFdz(Uz)};

double dUxdy = Split{0.0,dFdy(Ux)};
double dUydz = Split{0.0,dFdz(Uy)};
double dUzdx = Split{0.0,dFdx(Uz)};

double dUxdz = Split{0.0,dFdz(Ux)};
double dUydx = Split{0.0,dFdx(Uy)};
double dUzdy = Split{0.0,dFdy(Uz)};
</Parameter>
    <Parameter ID="Expression">Result = IsCond(Omegay,A) ?
                                   IsLeft ? +2.0*(-Uz[right]+Uz)/HX[x]-Omegay[right] :
                                   IsRight ? -2.0*(-Uz[left]+Uz)/HX[XM]-Omegay[left] :
                                   IsBottom ? -2.0*(-Ux[up]+Ux)/HZ[z]-Omegay[up] :
                                   IsTop ? +2.0*(-Ux[down]+Ux)/HZ_ZM-Omegay[down] :
                                   0.0 : dUxdz-dUzdx;
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqOmegay" ContID="Bound" Color="#FF0080" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="B_Omegaz" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="813" Top="598"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars">double dUxdx = Split{0.0,dFdx(Ux)};
double dUydy = Split{0.0,dFdy(Uy)};
double dUzdz = Split{0.0,dFdz(Uz)};

double dUxdy = Split{0.0,dFdy(Ux)};
double dUydz = Split{0.0,dFdz(Uy)};
double dUzdx = Split{0.0,dFdx(Uz)};

double dUxdz = Split{0.0,dFdz(Ux)};
double dUydx = Split{0.0,dFdx(Uy)};
double dUzdy = Split{0.0,dFdy(Uz)};
</Parameter>
    <Parameter ID="Expression">Result = IsCond(Omegaz,A) ?
                                   IsLeft ? -2.0*(-Uy[right]+Uy)/HX[x]-Omegaz[right] :
                                   IsRight ? +2.0*(-Uy[left]+Uy)/HX[XM]-Omegaz[left] :
                                   IsForw ? -2.0*(-Ux[back]+Ux)/HY[YM]-Omegaz[back] :
                                   IsBack ? +2.0*(-Ux[forw]+Ux)/HY[y]-Omegaz[forw] :
                                   0.0 : dUydx-dUxdy;
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqOmegaz" ContID="Bound" Color="#FF0080" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="S_Omegax" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="931" Top="465"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars">double dUxdx = Split{0.0,dFdx(Ux)};
double dUydy = Split{0.0,dFdy(Uy)};
double dUzdz = Split{0.0,dFdz(Uz)};

double dUxdy = Split{0.0,dFdy(Ux)};
double dUydz = Split{0.0,dFdz(Uy)};
double dUzdx = Split{0.0,dFdx(Uz)};

double dUxdz = Split{0.0,dFdz(Ux)};
double dUydx = Split{0.0,dFdx(Uy)};
double dUzdy = Split{0.0,dFdy(Uz)};
</Parameter>
    <Parameter ID="Expression">Split{0.0,dUxdx};</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqOmegax" ContID="S" Color="#8080FF" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="S_Omegaz" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="927" Top="653"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars">double dUxdx = Split{0.0,dFdx(Ux)};
double dUydy = Split{0.0,dFdy(Uy)};
double dUzdz = Split{0.0,dFdz(Uz)};

double dUxdy = Split{0.0,dFdy(Ux)};
double dUydz = Split{0.0,dFdz(Uy)};
double dUzdx = Split{0.0,dFdx(Uz)};

double dUxdz = Split{0.0,dFdz(Ux)};
double dUydx = Split{0.0,dFdx(Uy)};
double dUzdy = Split{0.0,dFdy(Uz)};
</Parameter>
    <Parameter ID="Expression">Split{0.0,dUzdz};</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqOmegaz" ContID="S" Color="#8080FF" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="S_Omegay" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="729" Top="549"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars">double dUxdx = Split{0.0,dFdx(Ux)};
double dUydy = Split{0.0,dFdy(Uy)};
double dUzdz = Split{0.0,dFdz(Uz)};

double dUxdy = Split{0.0,dFdy(Ux)};
double dUydz = Split{0.0,dFdz(Uy)};
double dUzdx = Split{0.0,dFdx(Uz)};

double dUxdz = Split{0.0,dFdz(Ux)};
double dUydx = Split{0.0,dFdx(Uy)};
double dUzdy = Split{0.0,dFdy(Uz)};
</Parameter>
    <Parameter ID="Expression">Split{0.0,dUydy};</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqOmegay" ContID="S" Color="#8080FF" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_WhirlEquation" ParentID="" ID="EqOmegax" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="920" Top="361"/>
   <Parameters NumItems="3">
    <Parameter ID="Handler">NULL</Parameter>
    <Parameter ID="NuMol">@D</Parameter>
    <Parameter ID="Kappa">1</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="1">
     <pContact ID="K" PublicID="K_Omegax" PublicName="K (Omegax)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="1">
     <pContact ID="Solver" PublicID="SolveOmegax" PublicName="Реш (Omegax)"/>
   </PublishedOutputs>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="Omegax" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_Omegax" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="Bound">
     <Link ElementID="B_Omegax" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="S">
     <Link ElementID="S_Omegax" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
  <Element ClassID="clsE_WhirlEquation" ParentID="" ID="EqOmegay" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="817" Top="466"/>
   <Parameters NumItems="3">
    <Parameter ID="Handler">NULL</Parameter>
    <Parameter ID="NuMol">@D</Parameter>
    <Parameter ID="Kappa">1</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="1">
     <pContact ID="K" PublicID="K_Omegay" PublicName="K (Omegay)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="1">
     <pContact ID="Solver" PublicID="SolveOmegay" PublicName="Реш (Omegay)"/>
   </PublishedOutputs>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="Omegay" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_Omegay" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="Bound">
     <Link ElementID="B_Omegay" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="S">
     <Link ElementID="S_Omegay" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
  <Element ClassID="clsE_WhirlEquation" ParentID="" ID="EqOmegaz" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="927" Top="549"/>
   <Parameters NumItems="3">
    <Parameter ID="Handler">NULL</Parameter>
    <Parameter ID="NuMol">@D</Parameter>
    <Parameter ID="Kappa">1</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="1">
     <pContact ID="K" PublicID="K_Omegaz" PublicName="K (Omegaz)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="1">
     <pContact ID="Solver" PublicID="SolveOmegaz" PublicName="Реш (Omegaz)"/>
   </PublishedOutputs>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="Omegaz" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_Omegaz" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="Bound">
     <Link ElementID="B_Omegaz" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="S">
     <Link ElementID="S_Omegaz" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
  <Element ClassID="clsE_PoissonEquation" ParentID="" ID="EqUx" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="863" Top="99"/>
   <Parameters NumItems="3">
    <Parameter ID="Handler">PoissonSolver</Parameter>
    <Parameter ID="NuMol">0.0</Parameter>
    <Parameter ID="Kappa">0.0</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="1">
     <pContact ID="Bound" PublicID="BoundUx" PublicName="Гран (Ux)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="1">
     <pContact ID="Solver" PublicID="SolveUx" PublicName="Реш (Ux)"/>
   </PublishedOutputs>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="Ux" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_Ux" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
  <Element ClassID="clsE_PoissonEquation" ParentID="" ID="EqUy" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="932" Top="208"/>
   <Parameters NumItems="3">
    <Parameter ID="Handler">PoissonSolver</Parameter>
    <Parameter ID="NuMol">0.0</Parameter>
    <Parameter ID="Kappa">0.0</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="1">
     <pContact ID="Bound" PublicID="BoundUy" PublicName="Гран (Uy)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="1">
     <pContact ID="Solver" PublicID="SolveUy" PublicName="Реш (Uy)"/>
   </PublishedOutputs>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="Uy" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_Uy" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
  <Element ClassID="clsE_PoissonEquation" ParentID="" ID="EqUz" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="799" Top="289"/>
   <Parameters NumItems="3">
    <Parameter ID="Handler">PoissonSolver</Parameter>
    <Parameter ID="NuMol">0.0</Parameter>
    <Parameter ID="Kappa">0.0</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="1">
     <pContact ID="Bound" PublicID="BoundUz" PublicName="Гран (Uz)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="1">
     <pContact ID="Solver" PublicID="SolveUz" PublicName="Реш (Uz)"/>
   </PublishedOutputs>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="Uz" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_Uz" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
 </Elements>
</System>
