<?xml version="1.0" encoding="windows-1251"?>
<!DOCTYPE System [
<!ELEMENT System (Elements)>
<!ATTLIST System
Lang CDATA #REQUIRED
>
<!ELEMENT Elements (Element*)>
<!ATTLIST Elements
NumItems CDATA #REQUIRED
>
<!ELEMENT Element (Show,Position,Parameters,InternalInputs,InternalOutputs,PublishedInputs,PublishedOutputs,InputLinks,OutputLinks)>
<!ATTLIST Element
ClassID CDATA #REQUIRED
ParentID CDATA #REQUIRED
ID ID #REQUIRED
Permanent (True | False) #REQUIRED
>
<!ELEMENT Show EMPTY>
<!ATTLIST Show
Class (True | False) #REQUIRED
Name (True | False) #REQUIRED
Image (True | False) #REQUIRED
>
<!ELEMENT Position EMPTY>
<!ATTLIST Position
Left CDATA #REQUIRED
Top CDATA #REQUIRED
>
<!ELEMENT Parameters (Parameter*)>
<!ATTLIST Parameters
NumItems CDATA #REQUIRED
>
<!ELEMENT Parameter (#PCDATA | EMPTY)*>
<!ATTLIST Parameter
ID CDATA #REQUIRED
>
<!ELEMENT InternalInputs (iContact*)>
<!ATTLIST InternalInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT InternalOutputs (iContact*)>
<!ATTLIST InternalOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT iContact EMPTY>
<!ATTLIST iContact
ID CDATA #REQUIRED
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
>
<!ELEMENT PublishedInputs (pContact*)>
<!ATTLIST PublishedInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT PublishedOutputs (pContact*)>
<!ATTLIST PublishedOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT pContact EMPTY>
<!ATTLIST pContact
ID CDATA #REQUIRED
PublicID CDATA #REQUIRED
PublicName CDATA #REQUIRED
>
<!ELEMENT InputLinks (Contact*)>
<!ELEMENT OutputLinks (Contact*)>
<!ELEMENT Contact (Link*)>
<!ATTLIST Contact
ID CDATA #REQUIRED
>
<!ELEMENT Link (Points?)>
<!ATTLIST Link
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
Color CDATA #IMPLIED
Informational (True | False) #REQUIRED
>
<!ELEMENT Points (#PCDATA | EMPTY)*>
<!ATTLIST Points
NumItems CDATA #REQUIRED
>
]>
<System Lang="">
 <Elements NumItems="129">
  <Element ID="S_UV" ClassID="clsE_Function" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="614" Top="1544"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression">Split{0.0,3.0*uvtAlpha*uvtBeta};</Parameter>
    <Parameter ID="Vars">vector uvieC0[i] = @[]uvQeC0{Drops}[i];
vector uvieC1[i] = @[]uvQeC1{Drops}[i]*1E6;
vector uvieC2[i] = @[]uvQeC2{Drops}[i]*1E12;
vector uvieC3[i] = @[]uvQeC3{Drops}[i]*1E18;
vector uvieC4[i] = @[]uvQeC4{Drops}[i]*1E24;
vector uvieC5[i] = @[]uvQeC5{Drops}[i]*1E30;
vector uviaC0[i] = @[]uvQaC0{Drops}[i];
vector uviaC1[i] = @[]uvQaC1{Drops}[i]*1E6;
vector uviaC2[i] = @[]uvQaC2{Drops}[i]*1E12;
vector uviaC3[i] = @[]uvQaC3{Drops}[i]*1E18;
vector uviaC4[i] = @[]uvQaC4{Drops}[i]*1E24;
vector uviaC5[i] = @[]uvQaC5{Drops}[i]*1E30;
vector uvigC0[i] = @[]uvgC0{Drops}[i];
vector uvigC1[i] = @[]uvgC1{Drops}[i]*1E6;
vector uvigC2[i] = @[]uvgC2{Drops}[i]*1E12;
vector uvigC3[i] = @[]uvgC3{Drops}[i]*1E18;
vector uvigC4[i] = @[]uvgC4{Drops}[i]*1E24;
vector uvigC5[i] = @[]uvgC5{Drops}[i]*1E30;

vector uviBeta[i] = Split{0.0,EMPTY[i] ? 0.0 :
                    Pi/4.0*
                      (
                       An[i]*(uvieC0[i]*XY4[i]+uvieC1[i]*XY5[i]+uvieC2[i]*XY6[i]+uvieC3[i]*XY7[i]+uvieC4[i]*XY8[i]+uvieC5[i]*XY9[i])+
                       Bn[i]*(uvieC0[i]*XY3[i]+uvieC1[i]*XY4[i]+uvieC2[i]*XY5[i]+uvieC3[i]*XY6[i]+uvieC4[i]*XY7[i]+uvieC5[i]*XY8[i])
                      )
                  };
vector uviAbs[i] = Split{0.0,EMPTY[i] ? 0.0 :
                    Pi/4.0*
                      (
                       An[i]*(uviaC0[i]*XY4[i]+uviaC1[i]*XY5[i]+uviaC2[i]*XY6[i]+uviaC3[i]*XY7[i]+uviaC4[i]*XY8[i]+uviaC5[i]*XY9[i])+
                       Bn[i]*(uviaC0[i]*XY3[i]+uviaC1[i]*XY4[i]+uviaC2[i]*XY5[i]+uviaC3[i]*XY6[i]+uviaC4[i]*XY7[i]+uviaC5[i]*XY8[i])
                      )
                 };
vector uviAsym[i] = Split{0.0,EMPTY[i] ? 0.0 :
                      (
                       An[i]*(uvigC0[i]*XY2[i]+uvigC1[i]*XY3[i]+uvigC2[i]*XY4[i]+uvigC3[i]*XY5[i]+uvigC4[i]*XY6[i]+uvigC5[i]*XY7[i])+
                       Bn[i]*(uvigC0[i]*XY1[i]+uvigC1[i]*XY2[i]+uvigC2[i]*XY3[i]+uvigC3[i]*XY4[i]+uvigC4[i]*XY5[i]+uvigC5[i]*XY6[i])
                      )/Nk[i]
                   };
vector uviAlbedo[i] = Split{0.0,EMPTY[i] ? 0.0 : (uviBeta[i]-uviAbs[i])/uviBeta[i]};
double uveBeta = @uvAirBeta+Sum{uviBeta[i]};
double uveScat = @uvAirAlbedo*@uvAirBeta+Sum{uviAlbedo[i]*uviBeta[i]};
double uvkAlbedo = uveScat/uveBeta;
double uvkAsymm = (@uvAirAlbedo*@uvAirBeta*@uvAirAsymmetry+Sum{uviAlbedo[i]*uviBeta[i]*uviAsym[i]})/uveScat;
double Pi = 3.1415926535897932;
double uvkAlbAsm = uvkAlbedo*uvkAsymm;
double uvtAlpha = uveBeta*(1-uvkAlbedo);
double uvtBeta = uveBeta*(1-uvkAlbAsm);
double uv_Ft = 3.0*uveBeta*uvkAlbedo/4.0/Pi;
double uvFt = uv_Ft*FUV;
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase">
     <Link ElementID="Drops" ContID="Define" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUV" ContID="S" Color="clYellow" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="B_UV" ClassID="clsE_Function" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="604" Top="1524"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression">      if (IsClosed(UV))
        {
         if (IsForw)   _fw(UV) = (uvk1a*UV[back]+HY[y-1]*SolarY*_fw(FUV)*@SurfaceAlbedo/Pi)/(uvk1a+HY[y-1]*(1-@SurfaceAlbedo));
         if (IsBack)   _bw(UV) = (uvk1a*UV[forw]-HY[y]*SolarY*  _bw(FUV)*@SurfaceAlbedo/Pi)/(uvk1a+HY[y]*(1-@SurfaceAlbedo));
         if (IsBottom) _bt(UV) = (uvk1a*UV[up]-HZ[z]*SolarZ*  _bt(FUV)*@SurfaceAlbedo/Pi)/(uvk1a+HZ[z]*(1-@SurfaceAlbedo));
         if (IsTop)    _tp(UV) = (uvk1a*UV[down]+HZ_ZM*SolarZ*  _tp(FUV)*@SurfaceAlbedo/Pi)/(uvk1a+HZ_ZM*(1-@SurfaceAlbedo));
         if (IsLeft)   _lf(UV) = (uvk1a*UV[right]-HX[x]*SolarX*  _lf(FUV)*@SurfaceAlbedo/Pi)/(uvk1a+HX[x]*(1-@SurfaceAlbedo));
         if (IsRight)  _rg(UV) = (uvk1a*UV[left]+HX[x-1]*SolarX*_rg(FUV)*@SurfaceAlbedo/Pi)/(uvk1a+HX[x-1]*(1-@SurfaceAlbedo));
        }
      else
        {
         if (IsForw)   _fw(UV) = (uvk1*UV[back]+HY[y-1]*uvFluxPi)/(uvk1+HY[y-1]);
         if (IsBack)   _bw(UV) = (uvk1*UV[forw]+HY[y]*uvFluxPi)/(uvk1+HY[y]);
         if (IsBottom) _bt(UV) = (uvk1*UV[up]+HZ[z]*uvFluxPi)/(uvk1+HZ[z]);
         if (IsTop)    _tp(UV) = (uvk1*UV[down]+HZ_ZM*uvFluxPi)/(uvk1+HZ_ZM);
         if (IsLeft)   _lf(UV) = (uvk1*UV[right]+HX[x]*uvFluxPi)/(uvk1+HX[x]);
         if (IsRight)  _rg(UV) = (uvk1*UV[left]+HX[x-1]*uvFluxPi)/(uvk1+HX[x-1]);
        }
</Parameter>
    <Parameter ID="Vars">double uvk1 = 2.0/3.0/uvtBeta;
double uvk1a = uvk1*(1+@SurfaceAlbedo);
double uvFluxPi = @uvDiffuseFlux/Pi;
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase"/>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUV" ContID="Bound" Color="#FF8080" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="K_UV" ClassID="clsE_Function" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="594" Top="1504"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression">Split{0.0,-uvFt*uvtBeta};</Parameter>
    <Parameter ID="Vars">vector uvieC0[i] = @[]uvQeC0{Drops}[i];
vector uvieC1[i] = @[]uvQeC1{Drops}[i]*1E6;
vector uvieC2[i] = @[]uvQeC2{Drops}[i]*1E12;
vector uvieC3[i] = @[]uvQeC3{Drops}[i]*1E18;
vector uvieC4[i] = @[]uvQeC4{Drops}[i]*1E24;
vector uvieC5[i] = @[]uvQeC5{Drops}[i]*1E30;
vector uviaC0[i] = @[]uvQaC0{Drops}[i];
vector uviaC1[i] = @[]uvQaC1{Drops}[i]*1E6;
vector uviaC2[i] = @[]uvQaC2{Drops}[i]*1E12;
vector uviaC3[i] = @[]uvQaC3{Drops}[i]*1E18;
vector uviaC4[i] = @[]uvQaC4{Drops}[i]*1E24;
vector uviaC5[i] = @[]uvQaC5{Drops}[i]*1E30;
vector uvigC0[i] = @[]uvgC0{Drops}[i];
vector uvigC1[i] = @[]uvgC1{Drops}[i]*1E6;
vector uvigC2[i] = @[]uvgC2{Drops}[i]*1E12;
vector uvigC3[i] = @[]uvgC3{Drops}[i]*1E18;
vector uvigC4[i] = @[]uvgC4{Drops}[i]*1E24;
vector uvigC5[i] = @[]uvgC5{Drops}[i]*1E30;

vector uviBeta[i] = Split{0.0,EMPTY[i] ? 0.0 :
                    Pi/4.0*
                      (
                       An[i]*(uvieC0[i]*XY4[i]+uvieC1[i]*XY5[i]+uvieC2[i]*XY6[i]+uvieC3[i]*XY7[i]+uvieC4[i]*XY8[i]+uvieC5[i]*XY9[i])+
                       Bn[i]*(uvieC0[i]*XY3[i]+uvieC1[i]*XY4[i]+uvieC2[i]*XY5[i]+uvieC3[i]*XY6[i]+uvieC4[i]*XY7[i]+uvieC5[i]*XY8[i])
                      )
                  };
vector uviAbs[i] = Split{0.0,EMPTY[i] ? 0.0 :
                    Pi/4.0*
                      (
                       An[i]*(uviaC0[i]*XY4[i]+uviaC1[i]*XY5[i]+uviaC2[i]*XY6[i]+uviaC3[i]*XY7[i]+uviaC4[i]*XY8[i]+uviaC5[i]*XY9[i])+
                       Bn[i]*(uviaC0[i]*XY3[i]+uviaC1[i]*XY4[i]+uviaC2[i]*XY5[i]+uviaC3[i]*XY6[i]+uviaC4[i]*XY7[i]+uviaC5[i]*XY8[i])
                      )
                 };
vector uviAsym[i] = Split{0.0,EMPTY[i] ? 0.0 :
                      (
                       An[i]*(uvigC0[i]*XY2[i]+uvigC1[i]*XY3[i]+uvigC2[i]*XY4[i]+uvigC3[i]*XY5[i]+uvigC4[i]*XY6[i]+uvigC5[i]*XY7[i])+
                       Bn[i]*(uvigC0[i]*XY1[i]+uvigC1[i]*XY2[i]+uvigC2[i]*XY3[i]+uvigC3[i]*XY4[i]+uvigC4[i]*XY5[i]+uvigC5[i]*XY6[i])
                      )/Nk[i]
                   };
vector uviAlbedo[i] = Split{0.0,EMPTY[i] ? 0.0 : (uviBeta[i]-uviAbs[i])/uviBeta[i]};
double uveBeta = @uvAirBeta+Sum{uviBeta[i]};
double uveScat = @uvAirAlbedo*@uvAirBeta+Sum{uviAlbedo[i]*uviBeta[i]};
double uvkAlbedo = uveScat/uveBeta;
double uvkAsymm = (@uvAirAlbedo*@uvAirBeta*@uvAirAsymmetry+Sum{uviAlbedo[i]*uviBeta[i]*uviAsym[i]})/uveScat;
double Pi = 3.1415926535897932;
double uvkAlbAsm = uvkAlbedo*uvkAsymm;
double uvtAlpha = uveBeta*(1-uvkAlbedo);
double uvtBeta = uveBeta*(1-uvkAlbAsm);
double uv_Ft = 3.0*uveBeta*uvkAlbedo/4.0/Pi;
double uvFt = uv_Ft*FUV;
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase">
     <Link ElementID="Drops" ContID="Define" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUV" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="UV_T" ClassID="clsE_Function" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="799" Top="125"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression">Split{0.0,uvtAlpha*(4.0*Pi*UV+FUV)/RO0/CC0};</Parameter>
    <Parameter ID="Vars">double TK = 273.15+T;
double RO0 = 352.984/TK;
double CC0 = 1.4*(718+0.1167*RO0);
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase"/>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqT" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="S_FUV" ClassID="clsE_Function" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="614" Top="1634"/>
   <Parameters NumItems="1">
    <Parameter ID="Expression">@uvSolarIntensity;</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase"/>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqFUV" ContID="S" Color="clYellow" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="K_FUV" ClassID="clsE_Function" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="594" Top="1614"/>
   <Parameters NumItems="1">
    <Parameter ID="Expression">uveBeta;</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase"/>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqFUV" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="FUV" ClassID="clsE_Var" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="504" Top="1594"/>
   <Parameters NumItems="2">
    <Parameter ID="FBase">fuv</Parameter>
    <Parameter ID="Desc">Интенсивность UV-прямого солнечного излучения</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqFUV" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="EqFUV" ClassID="clsE_SolarEquation" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="714" Top="1594"/>
   <Parameters NumItems="0"/>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="FUV" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="S">
     <Link ElementID="S_FUV" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_FUV" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Solver">
     <Link ElementID="Solver" ContID="Eqtn" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="EqUV" ClassID="clsE_PoissonEquation" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="714" Top="1484"/>
   <Parameters NumItems="0"/>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Bound">
     <Link ElementID="B_UV" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="Calc">
     <Link ElementID="UV" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="S">
     <Link ElementID="S_UV" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_UV" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Solver">
     <Link ElementID="Solver" ContID="Eqtn" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="UV" ClassID="clsE_Var" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="504" Top="1484"/>
   <Parameters NumItems="2">
    <Parameter ID="FBase">uv</Parameter>
    <Parameter ID="Desc">Интенсивность UV-диффузного излучения</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase">
     <Link ElementID="MainPhase" ContID="Define" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqUV" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="S_VIS" ClassID="clsE_Function" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="604" Top="1324"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression">Split{0.0,3.0*itAlpha*itBeta};</Parameter>
    <Parameter ID="Vars">vector iieC0[i] = @[]iQeC0{Drops}[i];
vector iieC1[i] = @[]iQeC1{Drops}[i]*1E6;
vector iieC2[i] = @[]iQeC2{Drops}[i]*1E12;
vector iieC3[i] = @[]iQeC3{Drops}[i]*1E18;
vector iieC4[i] = @[]iQeC4{Drops}[i]*1E24;
vector iieC5[i] = @[]iQeC5{Drops}[i]*1E30;
vector iiaC0[i] = @[]iQaC0{Drops}[i];
vector iiaC1[i] = @[]iQaC1{Drops}[i]*1E6;
vector iiaC2[i] = @[]iQaC2{Drops}[i]*1E12;
vector iiaC3[i] = @[]iQaC3{Drops}[i]*1E18;
vector iiaC4[i] = @[]iQaC4{Drops}[i]*1E24;
vector iiaC5[i] = @[]iQaC5{Drops}[i]*1E30;
vector iigC0[i] = @[]igC0{Drops}[i];
vector iigC1[i] = @[]igC1{Drops}[i]*1E6;
vector iigC2[i] = @[]igC2{Drops}[i]*1E12;
vector iigC3[i] = @[]igC3{Drops}[i]*1E18;
vector iigC4[i] = @[]igC4{Drops}[i]*1E24;
vector iigC5[i] = @[]igC5{Drops}[i]*1E30;

vector iiBeta[i] = Split{0.0,EMPTY[i] ? 0.0 :
                    Pi/4.0*
                      (
                       An[i]*(iieC0[i]*XY4[i]+iieC1[i]*XY5[i]+iieC2[i]*XY6[i]+iieC3[i]*XY7[i]+iieC4[i]*XY8[i]+iieC5[i]*XY9[i])+
                       Bn[i]*(iieC0[i]*XY3[i]+iieC1[i]*XY4[i]+iieC2[i]*XY5[i]+iieC3[i]*XY6[i]+iieC4[i]*XY7[i]+iieC5[i]*XY8[i])
                      )
                  };
vector iiAbs[i] = Split{0.0,EMPTY[i] ? 0.0 :
                    Pi/4.0*
                      (
                       An[i]*(iiaC0[i]*XY4[i]+iiaC1[i]*XY5[i]+iiaC2[i]*XY6[i]+iiaC3[i]*XY7[i]+iiaC4[i]*XY8[i]+iiaC5[i]*XY9[i])+
                       Bn[i]*(iiaC0[i]*XY3[i]+iiaC1[i]*XY4[i]+iiaC2[i]*XY5[i]+iiaC3[i]*XY6[i]+iiaC4[i]*XY7[i]+iiaC5[i]*XY8[i])
                      )
                 };
vector iiAsym[i] = Split{0.0,EMPTY[i] ? 0.0 :
                      (
                       An[i]*(iigC0[i]*XY2[i]+iigC1[i]*XY3[i]+iigC2[i]*XY4[i]+iigC3[i]*XY5[i]+iigC4[i]*XY6[i]+iigC5[i]*XY7[i])+
                       Bn[i]*(iigC0[i]*XY1[i]+iigC1[i]*XY2[i]+iigC2[i]*XY3[i]+iigC3[i]*XY4[i]+iigC4[i]*XY5[i]+iigC5[i]*XY6[i])
                      )/Nk[i]
                   };
vector iiAlbedo[i] = Split{0.0,EMPTY[i] ? 0.0 : (iiBeta[i]-iiAbs[i])/iiBeta[i]};
double ieBeta = @iAirBeta+Sum{iiBeta[i]};
double ieScat = @iAirAlbedo*@iAirBeta+Sum{iiAlbedo[i]*iiBeta[i]};
double ikAlbedo = ieScat/ieBeta;
double ikAsymm = (@iAirAlbedo*@iAirBeta*@iAirAsymmetry+Sum{iiAlbedo[i]*iiBeta[i]*iiAsym[i]})/ieScat;
double Pi = 3.1415926535897932;
double ikAlbAsm = ikAlbedo*ikAsymm;
double itAlpha = ieBeta*(1-ikAlbedo);
double itBeta = ieBeta*(1-ikAlbAsm);
double i_Ft = 3.0*ieBeta*ikAlbedo/4.0/Pi;
double iFt = i_Ft*FVIS;
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase">
     <Link ElementID="Drops" ContID="Define" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqVIS" ContID="S" Color="clYellow" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="B_VIS" ClassID="clsE_Function" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="594" Top="1304"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression">      if (IsClosed(VIS))
        {
         if (IsForw)   _fw(VIS) = (ik1a*VIS[back]+HY[y-1]*SolarY*_fw(FVIS)*@SurfaceAlbedo/Pi)/(ik1a+HY[y-1]*(1-@SurfaceAlbedo));
         if (IsBack)   _bw(VIS) = (ik1a*VIS[forw]-HY[y]*SolarY*  _bw(FVIS)*@SurfaceAlbedo/Pi)/(ik1a+HY[y]*(1-@SurfaceAlbedo));
         if (IsBottom) _bt(VIS) = (ik1a*VIS[up]-HZ[z]*SolarZ*  _bt(FVIS)*@SurfaceAlbedo/Pi)/(ik1a+HZ[z]*(1-@SurfaceAlbedo));
         if (IsTop)    _tp(VIS) = (ik1a*VIS[down]+HZ_ZM*SolarZ*  _tp(FVIS)*@SurfaceAlbedo/Pi)/(ik1a+HZ_ZM*(1-@SurfaceAlbedo));
         if (IsLeft)   _lf(VIS) = (ik1a*VIS[right]-HX[x]*SolarX*  _lf(FVIS)*@SurfaceAlbedo/Pi)/(ik1a+HX[x]*(1-@SurfaceAlbedo));
         if (IsRight)  _rg(VIS) = (ik1a*VIS[left]+HX[x-1]*SolarX*_rg(FVIS)*@SurfaceAlbedo/Pi)/(ik1a+HX[x-1]*(1-@SurfaceAlbedo));
        }
      else
        {
         if (IsForw)   _fw(VIS) = (ik1*VIS[back]+HY[y-1]*iFluxPi)/(ik1+HY[y-1]);
         if (IsBack)   _bw(VIS) = (ik1*VIS[forw]+HY[y]*iFluxPi)/(ik1+HY[y]);
         if (IsBottom) _bt(VIS) = (ik1*VIS[up]+HZ[z]*iFluxPi)/(ik1+HZ[z]);
         if (IsTop)    _tp(VIS) = (ik1*VIS[down]+HZ_ZM*iFluxPi)/(ik1+HZ_ZM);
         if (IsLeft)   _lf(VIS) = (ik1*VIS[right]+HX[x]*iFluxPi)/(ik1+HX[x]);
         if (IsRight)  _rg(VIS) = (ik1*VIS[left]+HX[x-1]*iFluxPi)/(ik1+HX[x-1]);
        }
</Parameter>
    <Parameter ID="Vars">double ik1 = 2.0/3.0/itBeta;
double ik1a = ik1*(1+@SurfaceAlbedo);
double iFluxPi = @iDiffuseFlux/Pi;
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase"/>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqVIS" ContID="Bound" Color="#FF8080" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="K_VIS" ClassID="clsE_Function" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="584" Top="1284"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression">Split{0.0,-iFt*itBeta};</Parameter>
    <Parameter ID="Vars">vector iieC0[i] = @[]iQeC0{Drops}[i];
vector iieC1[i] = @[]iQeC1{Drops}[i]*1E6;
vector iieC2[i] = @[]iQeC2{Drops}[i]*1E12;
vector iieC3[i] = @[]iQeC3{Drops}[i]*1E18;
vector iieC4[i] = @[]iQeC4{Drops}[i]*1E24;
vector iieC5[i] = @[]iQeC5{Drops}[i]*1E30;
vector iiaC0[i] = @[]iQaC0{Drops}[i];
vector iiaC1[i] = @[]iQaC1{Drops}[i]*1E6;
vector iiaC2[i] = @[]iQaC2{Drops}[i]*1E12;
vector iiaC3[i] = @[]iQaC3{Drops}[i]*1E18;
vector iiaC4[i] = @[]iQaC4{Drops}[i]*1E24;
vector iiaC5[i] = @[]iQaC5{Drops}[i]*1E30;
vector iigC0[i] = @[]igC0{Drops}[i];
vector iigC1[i] = @[]igC1{Drops}[i]*1E6;
vector iigC2[i] = @[]igC2{Drops}[i]*1E12;
vector iigC3[i] = @[]igC3{Drops}[i]*1E18;
vector iigC4[i] = @[]igC4{Drops}[i]*1E24;
vector iigC5[i] = @[]igC5{Drops}[i]*1E30;

vector iiBeta[i] = Split{0.0,EMPTY[i] ? 0.0 :
                    Pi/4.0*
                      (
                       An[i]*(iieC0[i]*XY4[i]+iieC1[i]*XY5[i]+iieC2[i]*XY6[i]+iieC3[i]*XY7[i]+iieC4[i]*XY8[i]+iieC5[i]*XY9[i])+
                       Bn[i]*(iieC0[i]*XY3[i]+iieC1[i]*XY4[i]+iieC2[i]*XY5[i]+iieC3[i]*XY6[i]+iieC4[i]*XY7[i]+iieC5[i]*XY8[i])
                      )
                  };
vector iiAbs[i] = Split{0.0,EMPTY[i] ? 0.0 :
                    Pi/4.0*
                      (
                       An[i]*(iiaC0[i]*XY4[i]+iiaC1[i]*XY5[i]+iiaC2[i]*XY6[i]+iiaC3[i]*XY7[i]+iiaC4[i]*XY8[i]+iiaC5[i]*XY9[i])+
                       Bn[i]*(iiaC0[i]*XY3[i]+iiaC1[i]*XY4[i]+iiaC2[i]*XY5[i]+iiaC3[i]*XY6[i]+iiaC4[i]*XY7[i]+iiaC5[i]*XY8[i])
                      )
                 };
vector iiAsym[i] = Split{0.0,EMPTY[i] ? 0.0 :
                      (
                       An[i]*(iigC0[i]*XY2[i]+iigC1[i]*XY3[i]+iigC2[i]*XY4[i]+iigC3[i]*XY5[i]+iigC4[i]*XY6[i]+iigC5[i]*XY7[i])+
                       Bn[i]*(iigC0[i]*XY1[i]+iigC1[i]*XY2[i]+iigC2[i]*XY3[i]+iigC3[i]*XY4[i]+iigC4[i]*XY5[i]+iigC5[i]*XY6[i])
                      )/Nk[i]
                   };
vector iiAlbedo[i] = Split{0.0,EMPTY[i] ? 0.0 : (iiBeta[i]-iiAbs[i])/iiBeta[i]};
double ieBeta = @iAirBeta+Sum{iiBeta[i]};
double ieScat = @iAirAlbedo*@iAirBeta+Sum{iiAlbedo[i]*iiBeta[i]};
double ikAlbedo = ieScat/ieBeta;
double ikAsymm = (@iAirAlbedo*@iAirBeta*@iAirAsymmetry+Sum{iiAlbedo[i]*iiBeta[i]*iiAsym[i]})/ieScat;
double Pi = 3.1415926535897932;
double ikAlbAsm = ikAlbedo*ikAsymm;
double itAlpha = ieBeta*(1-ikAlbedo);
double itBeta = ieBeta*(1-ikAlbAsm);
double i_Ft = 3.0*ieBeta*ikAlbedo/4.0/Pi;
double iFt = i_Ft*FVIS;
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase">
     <Link ElementID="Drops" ContID="Define" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqVIS" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="VIS_T" ClassID="clsE_Function" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="789" Top="103"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression">Split{0.0,itAlpha*(4.0*Pi*VIS+FVIS)/RO0/CC0};</Parameter>
    <Parameter ID="Vars">double TK = 273.15+T;
double RO0 = 352.984/TK;
double CC0 = 1.4*(718+0.1167*RO0);
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase"/>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqT" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="S_FVIS" ClassID="clsE_Function" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="604" Top="1414"/>
   <Parameters NumItems="1">
    <Parameter ID="Expression">@iSolarIntensity;</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase"/>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqFVIS" ContID="S" Color="clYellow" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="K_FVIS" ClassID="clsE_Function" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="584" Top="1394"/>
   <Parameters NumItems="1">
    <Parameter ID="Expression">ieBeta;</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Phase"/>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqFVIS" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="FVIS" ClassID="clsE_Var" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="494" Top="1374"/>
   <Parameters NumItems="2">
    <Parameter ID="FBase">fi</Parameter>
    <Parameter ID="Desc">Интенсивность VIS-прямого солнечного излучения</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqFVIS" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="EqFVIS" ClassID="clsE_SolarEquation" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="714" Top="1374"/>
   <Parameters NumItems="0"/>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="FVIS" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="S">
     <Link ElementID="S_FVIS" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_FVIS" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Solver">
     <Link ElementID="Solver" ContID="Eqtn" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ID="EqVIS" ClassID="clsE_PoissonEquation" ParentID="" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="714" Top="1264"/>
   <Parameters NumItems="0"/>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Bound">
     <Link ElementID="B_VIS" ContID="Val" Informational="False"/>
    </Contact>
    <Contact ID="Calc">