<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE System [
<!ELEMENT System (Elements)>
<!ATTLIST System
Lang CDATA #REQUIRED
>
<!ELEMENT Elements (Element*)>
<!ATTLIST Elements
NumItems CDATA #REQUIRED
>
<!ELEMENT Element (Show,Position,Parameters,InternalInputs,InternalOutputs,PublishedInputs,PublishedOutputs,InputLinks,OutputLinks)>
<!ATTLIST Element
ClassID CDATA #REQUIRED
ParentID CDATA #REQUIRED
ID ID #REQUIRED
Permanent (True | False) #REQUIRED
>
<!ELEMENT Show EMPTY>
<!ATTLIST Show
Class (True | False) #REQUIRED
Name (True | False) #REQUIRED
Image (True | False) #REQUIRED
>
<!ELEMENT Position EMPTY>
<!ATTLIST Position
Left CDATA #REQUIRED
Top CDATA #REQUIRED
>
<!ELEMENT Parameters (Parameter*)>
<!ATTLIST Parameters
NumItems CDATA #REQUIRED
>
<!ELEMENT Parameter (#PCDATA | EMPTY)*>
<!ATTLIST Parameter
ID CDATA #REQUIRED
>
<!ELEMENT InternalInputs (iContact*)>
<!ATTLIST InternalInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT InternalOutputs (iContact*)>
<!ATTLIST InternalOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT iContact EMPTY>
<!ATTLIST iContact
ID CDATA #REQUIRED
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
>
<!ELEMENT PublishedInputs (pContact*)>
<!ATTLIST PublishedInputs
NumItems CDATA #REQUIRED
>
<!ELEMENT PublishedOutputs (pContact*)>
<!ATTLIST PublishedOutputs
NumItems CDATA #REQUIRED
>
<!ELEMENT pContact EMPTY>
<!ATTLIST pContact
ID CDATA #REQUIRED
PublicID CDATA #REQUIRED
PublicName CDATA #REQUIRED
>
<!ELEMENT InputLinks (Contact*)>
<!ELEMENT OutputLinks (Contact*)>
<!ELEMENT Contact (Link*)>
<!ATTLIST Contact
ID CDATA #REQUIRED
>
<!ELEMENT Link (Points?)>
<!ATTLIST Link
ElementID IDREF #REQUIRED
ContID CDATA #REQUIRED
Color CDATA #IMPLIED
Informational (True | False) #REQUIRED
>
<!ELEMENT Points (#PCDATA | EMPTY)*>
<!ATTLIST Points
NumItems CDATA #REQUIRED
>
]>
<System Lang="">
 <Elements NumItems="13">
  <Element ClassID="clsE_Vector" ParentID="" ID="U" Permanent="True">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="407" Top="139"/>
   <Parameters NumItems="2">
    <Parameter ID="FBase">v</Parameter>
    <Parameter ID="Desc">Скорость</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="2">
     <pContact ID="PhasePrm" PublicID="PrmU" PublicName="Скорость"/>
     <pContact ID="Phase" PublicID="PhaseU" PublicName="Фаза (U)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Vx">
     <Link ElementID="Ux" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
    <Contact ID="Vy">
     <Link ElementID="Uy" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
    <Contact ID="Vz">
     <Link ElementID="Uz" ContID="Vector" Color="#FF8000" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Ux" Permanent="True">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="589" Top="150"/>
   <Parameters NumItems="2">
    <Parameter ID="Init">0</Parameter>
    <Parameter ID="Restrict">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="U" ContID="Vx" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqUx" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Uy" Permanent="True">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="588" Top="208"/>
   <Parameters NumItems="2">
    <Parameter ID="Init">0</Parameter>
    <Parameter ID="Restrict">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="U" ContID="Vy" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqUy" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Projection" ParentID="" ID="Uz" Permanent="True">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="586" Top="269"/>
   <Parameters NumItems="2">
    <Parameter ID="Init">0</Parameter>
    <Parameter ID="Restrict">Any</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks>
    <Contact ID="Vector">
     <Link ElementID="U" ContID="Vz" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqUz" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="K_Ux" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="739" Top="173"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression">Split{0.0,-1.0/@RO*dFdx(P)};</Parameter>
    <Parameter ID="Vars"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUx" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="K_Uy" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="714" Top="257"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression">Split{0.0,-1.0/@RO*dFdy(P)};</Parameter>
    <Parameter ID="Vars"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUy" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="K_Uz" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="704" Top="346"/>
   <Parameters NumItems="2">
    <Parameter ID="Expression">Split{0.0,-1.0/@RO*dFdz(P)};</Parameter>
    <Parameter ID="Vars"></Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqUz" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_Function" ParentID="" ID="K_P" Permanent="False">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="621" Top="485"/>
   <Parameters NumItems="2">
    <Parameter ID="Vars">double dUxdx = Split{0.0,dFdx(Ux)};
double dUydy = Split{0.0,dFdy(Uy)};
double dUzdz = Split{0.0,dFdz(Uz)};

double dUxdy = Split{0.0,dFdy(Ux)};
double dUydz = Split{0.0,dFdz(Uy)};
double dUzdx = Split{0.0,dFdx(Uz)};

double dUxdz = Split{0.0,dFdz(Ux)};
double dUydx = Split{0.0,dFdx(Uy)};
double dUzdy = Split{0.0,dFdy(Uz)};
</Parameter>
    <Parameter ID="Expression">Result = Split{0.0,-@RO*(dUxdx*dUxdx+dUydy*dUydy+dUzdz*dUzdz+
                            2.0*(dUydx*dUxdy+dUydz*dUzdy+dUxdz*dUzdx)
                            -0.1*DIV/TAU
                            -d2NFdx2(Nu,DIV)
                            -d2NFdy2(Nu,DIV)
                            -d2NFdz2(Nu,DIV))};
</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="0"/>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Val">
     <Link ElementID="EqP" ContID="K" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_PoissonEquation" ParentID="" ID="EqP" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="843" Top="423"/>
   <Parameters NumItems="3">
    <Parameter ID="Handler">PoissonSolver</Parameter>
    <Parameter ID="NuMol">0.0</Parameter>
    <Parameter ID="Kappa">0.0</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="2">
     <pContact ID="K" PublicID="KoeffP" PublicName="Коэфф (P)"/>
     <pContact ID="Bound" PublicID="BoundP" PublicName="Гран (P)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="1">
     <pContact ID="Solver" PublicID="SolveP" PublicName="Реш (P)"/>
   </PublishedOutputs>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="P" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_P" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
  <Element ClassID="clsE_Var" ParentID="" ID="P" Permanent="True">
   <Show Class="False" Name="True" Image="False"/>
   <Position Left="569" Top="394"/>
   <Parameters NumItems="4">
    <Parameter ID="Init">0</Parameter>
    <Parameter ID="Restrict">Any</Parameter>
    <Parameter ID="FBase">p</Parameter>
    <Parameter ID="Desc">Давление</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="2">
     <pContact ID="PhasePrm" PublicID="PrmP" PublicName="Давление"/>
     <pContact ID="Phase" PublicID="PhaseP" PublicName="Фаза (P)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="0"/>
   <InputLinks/>
   <OutputLinks>
    <Contact ID="Calc">
     <Link ElementID="EqP" ContID="Calc" Color="clBlack" Informational="False">
      <Points NumItems="0"/>
     </Link>
    </Contact>
   </OutputLinks>
  </Element>
  <Element ClassID="clsE_DynEquation" ParentID="" ID="EqUx" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="843" Top="86"/>
   <Parameters NumItems="3">
    <Parameter ID="Handler">NULL</Parameter>
    <Parameter ID="NuMol">@D</Parameter>
    <Parameter ID="Kappa">1</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="1">
     <pContact ID="Bound" PublicID="BoundUx" PublicName="Гран (Ux)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="1">
     <pContact ID="Solver" PublicID="SolveUx" PublicName="Реш (Ux)"/>
   </PublishedOutputs>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="Ux" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_Ux" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
  <Element ClassID="clsE_DynEquation" ParentID="" ID="EqUy" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="843" Top="200"/>
   <Parameters NumItems="3">
    <Parameter ID="Handler">NULL</Parameter>
    <Parameter ID="NuMol">@D</Parameter>
    <Parameter ID="Kappa">1</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="1">
     <pContact ID="Bound" PublicID="BoundUy" PublicName="Гран (Uy)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="1">
     <pContact ID="Solver" PublicID="SolveUy" PublicName="Реш (Uy)"/>
   </PublishedOutputs>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="Uy" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_Uy" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
  <Element ClassID="clsE_DynEquation" ParentID="" ID="EqUz" Permanent="False">
   <Show Class="True" Name="True" Image="False"/>
   <Position Left="843" Top="312"/>
   <Parameters NumItems="3">
    <Parameter ID="Handler">NULL</Parameter>
    <Parameter ID="NuMol">@D</Parameter>
    <Parameter ID="Kappa">1</Parameter>
   </Parameters>
   <InternalInputs NumItems="0"/>
   <InternalOutputs NumItems="0"/>
   <PublishedInputs NumItems="2">
     <pContact ID="K" PublicID="KoeffUz" PublicName="Коэфф (Uz)"/>
     <pContact ID="Bound" PublicID="BoundUz" PublicName="Гран (Uz)"/>
   </PublishedInputs>
   <PublishedOutputs NumItems="1">
     <pContact ID="Solver" PublicID="SolveUz" PublicName="Реш (Uz)"/>
   </PublishedOutputs>
   <InputLinks>
    <Contact ID="Calc">
     <Link ElementID="Uz" ContID="Calc" Informational="False"/>
    </Contact>
    <Contact ID="K">
     <Link ElementID="K_Uz" ContID="Val" Informational="False"/>
    </Contact>
   </InputLinks>
   <OutputLinks/>
  </Element>
 </Elements>
</System>
